"""Generate a static HTML status dashboard from posts_history/.

DROP-IN REPLACEMENT for dashboard.py — enhanced UI, same API surface.
Edit CSS_BASE / JS_BODY here for visual changes; docs/index.html is
regenerated by this script on every workflow run.
"""

import html
import json
import subprocess
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

HISTORY_DIR = Path(__file__).parent / "posts_history"
DOCS_DIR    = Path(__file__).parent / "docs"
DOCS_DIR.mkdir(exist_ok=True)

REPO          = "AbuAli85/LINKEDIN_POSTS"
WORKFLOW_FILE = "auto-post.yml"
ACTIONS_URL   = f"https://github.com/{REPO}/actions/workflows/{WORKFLOW_FILE}"


def _current_branch() -> str:
    try:
        r = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        return r.stdout.strip() or "main"
    except Exception:
        return "main"


PILLAR_COLOR = {
    "pain":       "#e8372a",
    "proof":      "#2a9a5c",
    "vision":     "#818cf8",
    "conversion": "#d4840a",
    "leadership": "#2e7de0",
    "ai":         "#06b6d4",
    "marketing":  "#d4840a",
}

CRON_WEEKDAYS  = {5, 0, 2}   # Sat=5, Mon=0, Wed=2
CRON_HOUR_UTC  = 5
MUSCAT_OFFSET  = 4


def _to_muscat(dt: datetime) -> str:
    m = dt + timedelta(hours=MUSCAT_OFFSET)
    return (
        m.strftime("%b %d, %Y · %I:%M %p Muscat")
        .replace(" 0", " ")
        .replace("AM", "am")
        .replace("PM", "pm")
    )


def load_posts() -> list[dict]:
    files = sorted(HISTORY_DIR.glob("*.json"), reverse=True)
    posts = []
    for f in files:
        try:
            p = json.loads(f.read_text(encoding="utf-8"))
            p["_filename"] = f.name
            posts.append(p)
        except Exception:
            continue
    return posts


def next_runs(n: int = 3) -> list[datetime]:
    now = datetime.now(timezone.utc)
    dt  = now.replace(hour=CRON_HOUR_UTC, minute=0, second=0, microsecond=0)
    if dt <= now:
        dt += timedelta(days=1)
    result = []
    for _ in range(14):
        if dt.weekday() in CRON_WEEKDAYS:
            result.append(dt)
            if len(result) >= n:
                break
        dt += timedelta(days=1)
    return result


def _token_health(posts: list[dict]) -> tuple[str, str]:
    published = [p for p in posts if p.get("published") and p.get("published_at")]
    if not published:
        return ("LinkedIn tokens expire after 60 days. Set a reminder to renew.", "info")
    newest = max(published, key=lambda p: p.get("published_at", ""))
    try:
        created   = datetime.fromisoformat(newest["published_at"].replace("Z", "+00:00"))
        expires   = created + timedelta(days=60)
        days_left = (expires - datetime.now(timezone.utc)).days
        if days_left <= 0:
            return ("Token has likely expired — renew immediately (see LINKEDIN_SETUP.md)", "error")
        if days_left <= 10:
            return (f"Token expires in ~{days_left} days — renew now", "error")
        if days_left <= 20:
            return (f"Token expires in ~{days_left} days — plan renewal soon", "warn")
        return (f"Token valid for ~{days_left} more days", "ok")
    except Exception:
        return ("", "")


def _badge(text: str, cls: str) -> str:
    return f'<span class="badge {cls}">{text}</span>'


# ---------------------------------------------------------------------------
# CSS — single source of truth. Dark editorial theme.
# Brand: black / red / white. Primary accent: #e8372a.
# @import must be the first statement — placed at top of CSS_BASE.
# ---------------------------------------------------------------------------
CSS_BASE = r"""
@import url('https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500;600&family=DM+Mono:wght@400;500&family=Instrument+Serif:ital@0;1&display=swap');

*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Geist',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
     background:#0b0b0c;color:#ede9e3;min-height:100vh;-webkit-font-smoothing:antialiased}
a{color:inherit;text-decoration:none}

/* ── SKIP + SR ── */
.skip-link{position:absolute;left:-9999px;top:8px;background:#e8372a;color:#fff;padding:8px 14px;border-radius:6px;z-index:300;font-size:.85rem;font-weight:600}
.skip-link:focus{left:8px}
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
:focus-visible{outline:2px solid #e8372a;outline-offset:2px;border-radius:4px}

/* ── TOPBAR ── */
.topbar{background:#111113;border-bottom:1px solid rgba(255,255,255,.07);
        padding:0 28px;display:flex;align-items:center;height:52px;gap:12px;
        position:sticky;top:0;z-index:50}
.logo{display:flex;align-items:center;gap:10px;font-size:13px;font-weight:500;letter-spacing:-.01em}
.logo-mark{width:26px;height:26px;border-radius:7px;background:#e8372a;
           display:flex;align-items:center;justify-content:center;
           font-size:11px;font-weight:700;color:#fff;letter-spacing:0;flex-shrink:0}
.logo-sep{color:rgba(255,255,255,.2);margin:0 4px}
.topbar-right{display:flex;align-items:center;gap:6px;margin-left:auto}
.updated{font-size:11px;color:rgba(255,255,255,.3);font-family:'DM Mono',monospace;margin-right:8px}
.tb-btn{display:inline-flex;align-items:center;gap:6px;padding:5px 12px;
        border-radius:6px;font-size:12px;font-weight:500;
        border:1px solid transparent;cursor:pointer;background:transparent;
        color:rgba(255,255,255,.45);transition:color .15s,background .15s,border-color .15s;
        min-height:32px;font-family:inherit}
.tb-btn:hover{color:#ede9e3;background:rgba(255,255,255,.05);border-color:rgba(255,255,255,.1)}
.tb-btn.primary{background:#e8372a;color:#fff;border-color:transparent}
.tb-btn.primary:hover{background:#c9301f}
.live-dot{width:6px;height:6px;border-radius:50%;background:#e8372a;animation:pulse 2s ease-in-out infinite;flex-shrink:0}
@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}

/* ── TOKEN BANNER ── */
.token-banner{padding:9px 28px;font-size:12px;display:flex;align-items:center;gap:8px}
.token-banner.warn{background:#2d1800;color:#d4840a;border-bottom:1px solid rgba(212,132,10,.2)}
.token-banner.error{background:#1f0505;color:#e8372a;border-bottom:1px solid rgba(232,55,42,.2)}
.token-banner.info{background:#05131f;color:#38bdf8;border-bottom:1px solid rgba(56,189,248,.15)}
.token-banner a{color:inherit;text-decoration:underline;opacity:.7}
.token-banner a:hover{opacity:1}

/* ── STATS ROW ── */
.statsbar{background:#111113;border-bottom:1px solid rgba(255,255,255,.07);
          padding:16px 28px;display:flex;flex-wrap:wrap;gap:10px;align-items:center}
.stat{background:#161618;border:1px solid rgba(255,255,255,.07);border-radius:10px;
      padding:12px 18px;text-align:center;min-width:72px;transition:border-color .15s}
.stat:hover{border-color:rgba(255,255,255,.13)}
.stat .n{font-size:22px;font-weight:600;color:#ede9e3;line-height:1;letter-spacing:-.03em}
.stat .l{font-size:10px;color:rgba(255,255,255,.35);text-transform:uppercase;letter-spacing:.07em;margin-top:4px}
.stat.green .n{color:#2a9a5c}
.stat.amber .n{color:#d4840a}
.stat.red   .n{color:#e8372a}
.stat.blue  .n{color:#2e7de0}
.pillar-pills{display:flex;flex-wrap:wrap;gap:6px;margin-left:8px}
.pillar-pill{border:1px solid;border-radius:20px;padding:3px 12px;font-size:11px;font-family:'DM Mono',monospace}
.pillar-pill b{color:#ede9e3;margin-left:4px}

/* ── SCHEDULE BAR ── */
.schedbar{background:#111113;border-bottom:1px solid rgba(255,255,255,.07);
          padding:10px 28px;display:flex;flex-wrap:wrap;gap:16px;align-items:center;font-size:12px}
.schedbar .lbl{font-size:10px;color:rgba(255,255,255,.3);text-transform:uppercase;letter-spacing:.08em}
.run-item{color:rgba(255,255,255,.4)}.run-item b{color:#ede9e3}
.run-pillar{text-transform:uppercase;font-size:.7rem;letter-spacing:.06em;font-weight:600}
.run-arrow{color:rgba(255,255,255,.2);margin:0 4px}

/* ── CONTENT ── */
.content{max-width:840px;margin:0 auto;padding:24px 28px 60px}
.section-lbl{font-size:10px;color:rgba(255,255,255,.3);text-transform:uppercase;
             letter-spacing:.1em;margin-bottom:14px;font-weight:600}

/* ── CARD ── */
.card{background:#111113;border:1px solid rgba(255,255,255,.07);
      border-left:3px solid rgba(255,255,255,.07);border-radius:12px;
      padding:16px 18px;margin-bottom:10px;transition:border-color .15s}
.card:hover{border-color:rgba(255,255,255,.13)}
.card-header{display:flex;flex-wrap:wrap;align-items:center;gap:8px;margin-bottom:10px}
.pillar-tag{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.07em;
            padding:2px 8px;border-radius:4px;border:1px solid;font-family:'DM Mono',monospace}

/* Badges */
.badge{font-size:10px;padding:3px 9px;border-radius:4px;font-weight:600;
       font-family:'DM Mono',monospace;letter-spacing:.03em}
.badge.published{background:rgba(42,154,92,.12);color:#2a9a5c;border:1px solid rgba(42,154,92,.25)}
.badge.approved {background:rgba(46,125,224,.12);color:#2e7de0;border:1px solid rgba(46,125,224,.25)}
.badge.draft    {background:rgba(212,132,10,.12);color:#d4840a;border:1px solid rgba(212,132,10,.25)}
.badge.failed   {background:rgba(232,55,42,.12) ;color:#e8372a;border:1px solid rgba(232,55,42,.25)}
.badge.dry-run  {background:rgba(255,255,255,.05);color:rgba(255,255,255,.4);border:1px solid rgba(255,255,255,.1)}

.meta-right{margin-left:auto;display:flex;gap:8px;align-items:center}
.model-tag{font-size:10px;background:rgba(129,140,248,.1);color:#818cf8;
           border:1px solid rgba(129,140,248,.2);padding:2px 8px;border-radius:4px;
           font-family:'DM Mono',monospace}
.date{font-size:11px;color:rgba(255,255,255,.3);font-family:'DM Mono',monospace}

.topic{font-size:14px;font-weight:500;color:#ede9e3;margin-bottom:8px;line-height:1.4}
.fmt-row{margin-bottom:8px}
.fmt-tag{font-size:11px;color:rgba(255,255,255,.35);background:rgba(255,255,255,.04);
         border:1px solid rgba(255,255,255,.07);border-radius:4px;padding:2px 8px}

/* Alerts */
.alert{border-radius:6px;padding:8px 12px;font-size:12px;margin-bottom:10px;line-height:1.5}
.alert.warn {background:rgba(212,132,10,.1) ;border:1px solid rgba(212,132,10,.25);color:#d4840a}
.alert.error{background:rgba(232,55,42,.1)  ;border:1px solid rgba(232,55,42,.25) ;color:#e8372a}

/* Post text */
.post-text{font-size:13px;line-height:1.8;color:rgba(255,255,255,.6);
           white-space:pre-wrap;word-break:break-word}
.post-text.collapsed{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}
.expand-btn{background:none;border:none;color:#e8372a;font-size:12px;cursor:pointer;
            padding:8px 0;display:block;margin-top:6px;min-height:32px;font-family:inherit}
.expand-btn:hover{color:#f87171}

/* Card footer */
.card-footer{display:flex;align-items:center;gap:8px;margin-top:14px;flex-wrap:wrap}
.bar-track{flex:1;height:3px;background:rgba(255,255,255,.08);border-radius:2px;overflow:hidden;min-width:60px}
.bar-fill{height:100%;border-radius:2px}
.bar-fill.ok  {background:#2a9a5c}
.bar-fill.warn{background:#d4840a}
.chars{font-size:11px;font-family:'DM Mono',monospace}
.chars.ok  {color:#2a9a5c}
.chars.warn{color:#d4840a}
.retries{font-size:11px;color:#d4840a;font-family:'DM Mono',monospace}

.icon-btn{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);
          color:rgba(255,255,255,.4);font-size:11px;padding:5px 12px;border-radius:6px;
          cursor:pointer;transition:all .15s;min-height:32px;font-family:inherit;
          display:inline-flex;align-items:center;gap:5px}
.icon-btn:hover{background:rgba(255,255,255,.07);color:#ede9e3;border-color:rgba(255,255,255,.15)}
.icon-btn.copied{border-color:rgba(42,154,92,.4);color:#2a9a5c}
.li-link{font-size:11px;background:rgba(46,125,224,.08);color:#2e7de0;
         border:1px solid rgba(46,125,224,.2);border-radius:6px;padding:5px 11px;
         min-height:32px;display:inline-flex;align-items:center;gap:5px;
         transition:all .15s;font-family:inherit}
.li-link:hover{background:rgba(46,125,224,.15);border-color:rgba(46,125,224,.35)}

/* Review actions */
.review-actions{display:flex;flex-wrap:wrap;align-items:center;gap:7px;
                padding:10px 0 4px;border-top:1px solid rgba(255,255,255,.06);margin-top:8px}
.review-label{font-size:10px;color:rgba(255,255,255,.3);text-transform:uppercase;
              letter-spacing:.08em;margin-right:2px}
.rev-btn{border:none;font-size:11px;font-weight:500;padding:6px 13px;border-radius:6px;
         cursor:pointer;transition:all .15s;min-height:32px;font-family:inherit}
.rev-changes{background:rgba(212,132,10,.1);color:#d4840a;border:1px solid rgba(212,132,10,.25)}
.rev-changes:hover{background:rgba(212,132,10,.2)}
.rev-edit   {background:rgba(129,140,248,.1);color:#818cf8;border:1px solid rgba(129,140,248,.2)}
.rev-edit:hover{background:rgba(129,140,248,.18)}
.rev-recreate{background:rgba(255,255,255,.04);color:rgba(255,255,255,.4);
              border:1px solid rgba(255,255,255,.08)}
.rev-recreate:hover{color:#ede9e3;border-color:rgba(255,255,255,.18)}
.approve-btn{background:#e8372a;border:none;color:#fff;font-size:12px;font-weight:600;
             padding:7px 16px;border-radius:6px;cursor:pointer;transition:background .15s;
             min-height:32px;font-family:inherit}
.approve-btn:hover{background:#c9301f}

/* Metrics row */
.metrics-row{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-bottom:10px}
.metric-item{font-size:11px;color:rgba(255,255,255,.4);background:rgba(255,255,255,.04);
             border:1px solid rgba(255,255,255,.07);border-radius:4px;padding:2px 8px;
             font-family:'DM Mono',monospace}
.quality-score{font-size:11px;color:#d4840a;background:rgba(212,132,10,.1);
               border:1px solid rgba(212,132,10,.25);border-radius:4px;padding:2px 8px;
               font-weight:600;font-family:'DM Mono',monospace}
.hook-tag{font-size:11px;color:#818cf8;background:rgba(129,140,248,.1);
          border:1px solid rgba(129,140,248,.2);border-radius:4px;padding:2px 8px;
          font-family:'DM Mono',monospace}

/* Empty state */
.empty{text-align:center;padding:60px 20px;color:rgba(255,255,255,.3);font-size:14px;line-height:2.4}
.empty a{color:#e8372a;border-bottom:1px solid rgba(232,55,42,.4)}

/* ── MODALS ── */
.modal-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.8);
               z-index:200;align-items:center;justify-content:center;
               backdrop-filter:blur(4px)}
.modal-overlay.open{display:flex}
.modal-box{background:#161618;border:1px solid rgba(255,255,255,.1);border-radius:14px;
           padding:28px 30px;max-width:560px;width:90%;max-height:88vh;overflow-y:auto}
.modal-box h3{color:#ede9e3;font-size:15px;font-weight:600;margin-bottom:18px}
.modal-field{margin-bottom:14px}
.modal-label{font-size:11px;color:rgba(255,255,255,.35);margin-bottom:5px;
             display:block;text-transform:uppercase;letter-spacing:.06em;font-weight:600}
.modal-preview{font-size:12px;color:rgba(255,255,255,.5);background:#0b0b0c;
               border-radius:6px;padding:10px 12px;line-height:1.7;
               max-height:120px;overflow-y:auto;white-space:pre-wrap;word-break:break-word}
.modal-path{font-size:12px;color:rgba(255,255,255,.35);font-family:'DM Mono',monospace;
            background:#0b0b0c;padding:6px 10px;border-radius:5px;display:block}
.modal-input{width:100%;padding:9px 12px;background:#0b0b0c;
             border:1px solid rgba(255,255,255,.1);border-radius:7px;
             color:#ede9e3;font-size:13px;outline:none;transition:border-color .15s;
             font-family:inherit}
.modal-input:focus{border-color:rgba(232,55,42,.5)}
.modal-textarea{width:100%;padding:9px 12px;background:#0b0b0c;
                border:1px solid rgba(255,255,255,.1);border-radius:7px;
                color:#ede9e3;font-size:13px;outline:none;transition:border-color .15s;
                font-family:inherit;resize:vertical;min-height:100px;line-height:1.6}
.modal-textarea:focus{border-color:rgba(232,55,42,.5)}
.modal-hint{font-size:11px;color:rgba(255,255,255,.25);margin-top:5px;line-height:1.5}
.modal-status{font-size:12px;min-height:18px;margin-bottom:12px}
.modal-actions{display:flex;gap:10px;margin-top:4px}
.modal-confirm{background:#e8372a;color:#fff;border:none;padding:10px 20px;
               border-radius:7px;cursor:pointer;font-size:13px;font-weight:600;
               min-height:40px;font-family:inherit;transition:background .15s}
.modal-confirm:hover{background:#c9301f}
.modal-confirm:disabled{background:#333;color:rgba(255,255,255,.3);cursor:default}
.modal-confirm.approve-green{background:#2a9a5c}
.modal-confirm.approve-green:hover{background:#1d7a47}
.modal-cancel{background:rgba(255,255,255,.05);color:rgba(255,255,255,.5);
              border:1px solid rgba(255,255,255,.1);padding:10px 18px;
              border-radius:7px;cursor:pointer;font-size:13px;min-height:40px;
              font-family:inherit;transition:all .15s}
.modal-cancel:hover{color:#ede9e3;border-color:rgba(255,255,255,.2)}
.char-counter{font-size:11px;color:rgba(255,255,255,.3);margin-top:4px;
              font-family:'DM Mono',monospace;text-align:right}

/* ── ENGAGEMENT ── */
.eng-card{background:#111113;border:1px solid rgba(255,255,255,.07);border-radius:10px;
          padding:14px 16px;margin-bottom:10px}
.eng-header{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-bottom:8px}
.eng-badge{font-size:10px;font-weight:600;padding:2px 8px;border-radius:4px;
           font-family:'DM Mono',monospace}
.eng-meta{font-size:11px;color:rgba(255,255,255,.3);margin-left:auto}
.eng-comment{font-size:13px;color:rgba(255,255,255,.55);background:rgba(255,255,255,.04);
             border-radius:6px;padding:9px 12px;margin-bottom:8px;line-height:1.6}
.eng-risk-note{font-size:11px;color:#d4840a;background:rgba(212,132,10,.1);
               border-radius:5px;padding:5px 10px;margin-bottom:8px}
.eng-replies{display:flex;flex-direction:column;gap:5px;margin-bottom:9px}
.reply-opt{font-size:12px;color:rgba(255,255,255,.4);background:rgba(255,255,255,.04);
           border:1px solid rgba(255,255,255,.07);border-radius:5px;padding:7px 11px;line-height:1.6}
.reply-optrec{border-color:rgba(129,140,248,.35);color:#c7d2fe}
.reply-idx{font-size:11px;color:rgba(255,255,255,.3);font-weight:600;margin-right:4px}
.eng-cmd{font-size:11px;color:rgba(255,255,255,.3)}
.eng-cmd code{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.08);
              border-radius:4px;padding:2px 7px;font-family:'DM Mono',monospace}
.rp-item{font-size:12px;color:#2a9a5c;background:rgba(42,154,92,.08);border-radius:5px;
         padding:5px 10px;margin-bottom:5px}
.leads-table{display:flex;flex-direction:column;gap:6px}
.lead-row{display:flex;flex-wrap:wrap;align-items:center;gap:10px;
          background:#111113;border:1px solid rgba(255,255,255,.07);
          border-radius:8px;padding:9px 13px}
.lead-name{font-size:13px;color:#ede9e3;font-weight:600;min-width:100px}
.lead-count{font-size:11px;color:#818cf8;background:rgba(129,140,248,.1);
            border:1px solid rgba(129,140,248,.2);border-radius:4px;padding:2px 8px;
            font-family:'DM Mono',monospace}
.lead-comment{font-size:12px;color:rgba(255,255,255,.35);flex:1}

/* ── FOOTER ── */
footer{max-width:840px;margin:20px auto 0;padding:18px 28px 32px;
       border-top:1px solid rgba(255,255,255,.06);
       color:rgba(255,255,255,.25);font-size:12px;line-height:1.8}
footer a{color:rgba(255,255,255,.3);border-bottom:1px dotted rgba(255,255,255,.15)}
footer a:hover{color:#ede9e3}

/* ── TOAST ── */
#toast-container{position:fixed;bottom:24px;right:24px;z-index:250;
                 display:flex;flex-direction:column;gap:8px;pointer-events:none;
                 max-width:min(400px,calc(100vw - 48px))}
.toast{pointer-events:auto;background:#161618;border:1px solid rgba(255,255,255,.1);
       border-radius:10px;padding:12px 14px;display:flex;gap:10px;align-items:flex-start;
       box-shadow:0 4px 16px rgba(0,0,0,.5);font-size:13px;line-height:1.5;
       opacity:0;transform:translateY(8px);
       transition:opacity .2s cubic-bezier(.16,1,.3,1),transform .2s cubic-bezier(.16,1,.3,1)}
.toast.in{opacity:1;transform:translateY(0)}
.toast.out{opacity:0;transform:translateX(10px);transition-duration:.18s;transition-timing-function:ease-in}
.toast.success{background:rgba(42,154,92,.12);border-color:rgba(42,154,92,.25);color:#2a9a5c}
.toast.error  {background:rgba(232,55,42,.1); border-color:rgba(232,55,42,.25); color:#e8372a}
.toast.warning{background:rgba(212,132,10,.1);border-color:rgba(212,132,10,.25);color:#d4840a}
.toast.info   {background:rgba(46,125,224,.1); border-color:rgba(46,125,224,.25);color:#2e7de0}
.toast-icon{font-size:14px;flex-shrink:0;line-height:1.5}
.toast-body{flex:1;color:inherit}
.toast-close{background:transparent;border:none;color:inherit;opacity:.5;cursor:pointer;
             padding:0 2px;font-size:16px;line-height:1;min-height:24px;min-width:24px}
.toast-close:hover{opacity:1}
@media(prefers-reduced-motion:reduce){.toast{transition:opacity .01s;transform:none}.toast.out{transform:none}}

/* ── FILTER BAR ── */
.filter-bar{max-width:840px;margin:0 auto;padding:16px 28px 4px;display:flex;flex-wrap:wrap;gap:6px}
.filter-chip{display:inline-flex;align-items:center;gap:5px;padding:5px 12px;border-radius:20px;
             font-size:12px;font-weight:500;cursor:pointer;transition:all .15s;
             background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.09);
             color:rgba(255,255,255,.45);min-height:30px;font-family:inherit}
.filter-chip:hover{color:#ede9e3;border-color:rgba(255,255,255,.18)}
.filter-chip.active{background:rgba(232,55,42,.1);border-color:rgba(232,55,42,.3);color:#e8372a}
.filter-chip .count{font-size:10px;background:rgba(255,255,255,.07);padding:1px 6px;
                    border-radius:10px;font-family:'DM Mono',monospace;margin-left:2px}
.filter-chip.active .count{background:rgba(232,55,42,.15)}

/* ── RESPONSIVE ── */
@media(max-width:640px){
  .topbar,.statsbar,.schedbar,.content,.filter-bar{padding-left:16px;padding-right:16px}
  .topbar-right .updated,.topbar-right .tb-btn:not(.primary){display:none}
  .stat{padding:10px 14px}
  .modal-box{padding:20px 18px}
  .filter-chip{font-size:11px;padding:4px 10px}
  .card{padding:14px 14px}
  .review-actions{gap:5px}
  .card-footer{gap:5px}
  .meta-right{flex-wrap:wrap;gap:4px}
}
"""


# ---------------------------------------------------------------------------
# JS — behaviour: modals, toast, clipboard, expand, PAT storage, refresh.
# _REPO / _WORKFLOW / _BRANCH consts injected by generate().
# ---------------------------------------------------------------------------
JS_BODY = r"""
var _approveSourceBtn = null;
var _reviseSourceBtn  = null;
var _editSourceBtn    = null;
var _toastSeq = 0;

/* Focus trap inside modals */
document.querySelectorAll('.modal-box').forEach(function(box) {
  box.addEventListener('keydown', function(e) {
    if (e.key !== 'Tab') return;
    var sel = 'a[href],button:not([disabled]),textarea,input,[tabindex]:not([tabindex="-1"])';
    var els = [].slice.call(box.querySelectorAll(sel));
    if (!els.length) return;
    var first = els[0], last = els[els.length - 1];
    if (e.shiftKey) { if (document.activeElement === first) { e.preventDefault(); last.focus(); } }
    else            { if (document.activeElement === last)  { e.preventDefault(); first.focus(); } }
  });
});

document.addEventListener('keydown', function(e) {
  if (e.key !== 'Escape') return;
  var open = document.querySelector('.modal-overlay.open');
  if (open) {
    if (open.id === 'revise-modal')       closeReviseModal();
    else if (open.id === 'edit-modal')    closeEditModal();
    else if (open.id === 'approve-modal') closeApproveModal();
  }
});

/* Expand / collapse post text */
function toggle(i) {
  var t = document.getElementById('pt-' + i);
  var b = document.querySelector('#post-' + i + ' .expand-btn');
  if (t.classList.contains('collapsed')) {
    t.classList.remove('collapsed');
    b.setAttribute('aria-expanded', 'true');
    b.innerHTML = 'Show less &#9650;';
  } else {
    t.classList.add('collapsed');
    b.setAttribute('aria-expanded', 'false');
    b.innerHTML = 'Show more &#9660;';
  }
}

/* Copy post text */
function copyPost(i) {
  var el = document.getElementById('pt-' + i);
  var collapsed = el.classList.contains('collapsed');
  if (collapsed) el.classList.remove('collapsed');
  var text = el.innerText;
  if (collapsed) el.classList.add('collapsed');
  navigator.clipboard.writeText(text).then(function() {
    var btn = document.getElementById('copy-' + i);
    btn.innerHTML = '&#10003; Copied';
    btn.classList.add('copied');
    setTimeout(function() { btn.innerHTML = '&#128203; Copy'; btn.classList.remove('copied'); }, 2200);
    toast('Copied to clipboard.', { variant: 'success' });
  });
}

/* PAT helpers */
function _getPat() { return localStorage.getItem('gh_pat') || ''; }
function _setPat(v) { if (v) localStorage.setItem('gh_pat', v); }
function clearPat() { localStorage.removeItem('gh_pat'); toast('GitHub token cleared.', { variant: 'info' }); }

/* ── REVISE MODAL ── */
function showReviseModal(btn) {
  _reviseSourceBtn = btn;
  var path = btn.getAttribute('data-path');
  document.getElementById('revise-draft-path').value = path;
  document.getElementById('revise-path-display').textContent = path;
  document.getElementById('revise-notes').value = '';
  document.getElementById('revise-status').textContent = '';
  document.getElementById('revise-pat').value = _getPat();
  var cb = document.getElementById('revise-confirm-btn');
  cb.textContent = '✎ Request Changes'; cb.disabled = false;
  document.getElementById('revise-modal').classList.add('open');
  setTimeout(function() { document.getElementById('revise-notes').focus(); }, 50);
}
function closeReviseModal() {
  document.getElementById('revise-modal').classList.remove('open');
  if (_reviseSourceBtn) _reviseSourceBtn.focus();
}
document.getElementById('revise-modal').addEventListener('click', function(e) { if (e.target === this) closeReviseModal(); });

async function confirmRevise() {
  var pat   = document.getElementById('revise-pat').value.trim();
  var notes = document.getElementById('revise-notes').value.trim();
  var path  = document.getElementById('revise-draft-path').value;
  var st    = document.getElementById('revise-status');
  var cb    = document.getElementById('revise-confirm-btn');
  if (!pat)   { st.textContent = 'Enter your GitHub PAT.'; st.style.color = '#e8372a'; return; }
  if (!notes) { st.textContent = 'Describe what needs to change.'; st.style.color = '#e8372a'; return; }
  _setPat(pat);
  cb.textContent = 'Triggering…'; cb.disabled = true; st.textContent = '';
  try {
    var resp = await fetch(
      'https://api.github.com/repos/' + _REPO + '/actions/workflows/' + _WORKFLOW + '/dispatches',
      { method: 'POST',
        headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
        body: JSON.stringify({ ref: _BRANCH, inputs: { action: 'revise_draft', draft_file: path, revision_notes: notes } }) }
    );
    if (resp.status === 204) {
      closeReviseModal();
      toast('Revision requested — Claude is rewriting the draft.', { variant: 'success' });
    } else {
      var e = await resp.json().catch(function() { return {}; });
      st.textContent = 'Error ' + resp.status + ': ' + (e.message || 'check your PAT');
      st.style.color = '#e8372a'; cb.textContent = '✎ Request Changes'; cb.disabled = false;
    }
  } catch(e) { st.textContent = 'Network error: ' + e.message; st.style.color = '#e8372a'; cb.textContent = '✎ Request Changes'; cb.disabled = false; }
}

/* ── EDIT MODAL ── */
function showEditModal(btn) {
  _editSourceBtn = btn;
  var path    = btn.getAttribute('data-path');
  var preview = btn.getAttribute('data-preview');
  document.getElementById('edit-draft-path').value = path;
  var ta = document.getElementById('edit-content');
  ta.value = preview;
  document.getElementById('edit-charcount').textContent = preview.length + ' chars';
  ta.oninput = function() { document.getElementById('edit-charcount').textContent = ta.value.length + ' chars'; };
  document.getElementById('edit-status').textContent = '';
  document.getElementById('edit-pat').value = _getPat();
  var cb = document.getElementById('edit-confirm-btn');
  cb.textContent = '💾 Save Edit'; cb.disabled = false;
  document.getElementById('edit-modal').classList.add('open');
  setTimeout(function() { ta.focus(); }, 50);
}
function closeEditModal() {
  document.getElementById('edit-modal').classList.remove('open');
  if (_editSourceBtn) _editSourceBtn.focus();
}
document.getElementById('edit-modal').addEventListener('click', function(e) { if (e.target === this) closeEditModal(); });

async function confirmEdit() {
  var pat     = document.getElementById('edit-pat').value.trim();
  var path    = document.getElementById('edit-draft-path').value;
  var content = document.getElementById('edit-content').value;
  var st      = document.getElementById('edit-status');
  var cb      = document.getElementById('edit-confirm-btn');
  if (!pat)           { st.textContent = 'Enter your GitHub PAT.'; st.style.color = '#e8372a'; return; }
  if (!content.trim()){ st.textContent = 'Post text cannot be empty.'; st.style.color = '#e8372a'; return; }
  _setPat(pat);
  cb.textContent = 'Saving…'; cb.disabled = true; st.textContent = '';
  try {
    var metaResp = await fetch(
      'https://api.github.com/repos/' + _REPO + '/contents/' + path,
      { headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json' } }
    );
    if (!metaResp.ok) { var ge = await metaResp.json().catch(function(){ return {}; }); throw new Error('Could not read file: ' + (ge.message || metaResp.status)); }
    var meta = await metaResp.json();
    var currentJson = JSON.parse(atob(meta.content.replace(/\n/g,'')));
    currentJson.post = content; currentJson.char_count = content.length;
    currentJson.manually_edited = true; currentJson.edited_at = new Date().toISOString();
    var newContent = btoa(unescape(encodeURIComponent(JSON.stringify(currentJson, null, 2))));
    var putResp = await fetch(
      'https://api.github.com/repos/' + _REPO + '/contents/' + path,
      { method: 'PUT',
        headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: 'edit: manual revision via dashboard', content: newContent, sha: meta.sha, branch: _BRANCH }) }
    );
    if (putResp.status === 200 || putResp.status === 201) {
      closeEditModal();
      toast('Edit saved. Refresh in ~30 s to see it.', { variant: 'success' });
    } else {
      var e2 = await putResp.json().catch(function(){ return {}; });
      st.textContent = 'Error ' + putResp.status + ': ' + (e2.message || 'check PAT scope');
      st.style.color = '#e8372a'; cb.textContent = '💾 Save Edit'; cb.disabled = false;
    }
  } catch(e) { st.textContent = 'Error: ' + e.message; st.style.color = '#e8372a'; cb.textContent = '💾 Save Edit'; cb.disabled = false; }
}

/* ── RECREATE ── */
function confirmRecreate(btn) {
  var pillar = btn.getAttribute('data-pillar') || 'same pillar';
  if (!confirm('Regenerate a new draft for the ' + pillar + ' pillar?\nThe current draft stays in posts_history.')) return;
  var pat = _getPat();
  if (!pat) { pat = prompt('GitHub PAT (workflow scope):'); if (!pat) return; _setPat(pat); }
  fetch('https://api.github.com/repos/' + _REPO + '/actions/workflows/' + _WORKFLOW + '/dispatches',
    { method: 'POST',
      headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
      body: JSON.stringify({ ref: _BRANCH, inputs: { action: 'generate_draft', pillar: pillar } }) }
  ).then(function(r) {
    if (r.status === 204) toast('New ' + pillar + ' draft generating — refresh in ~60 s.', { variant: 'success' });
    else r.json().then(function(e){ toast('Error ' + r.status + ': ' + (e.message || 'check PAT'), { variant: 'error' }); })
         .catch(function(){ toast('Error ' + r.status, { variant: 'error' }); });
  }).catch(function(e){ toast('Network error: ' + e.message, { variant: 'error' }); });
}

/* ── APPROVE MODAL ── */
function showApproveModal(btn) {
  _approveSourceBtn = btn;
  var path    = btn.getAttribute('data-path');
  var preview = btn.getAttribute('data-preview');
  var day     = btn.getAttribute('data-publish-day') || 'scheduled day';
  document.getElementById('modal-draft-path').value = path;
  document.getElementById('modal-path-display').textContent = path;
  document.getElementById('modal-preview').textContent = preview;
  document.getElementById('approve-modal-title').textContent = '✓ Approve — publishes ' + day;
  var copyBtn = document.getElementById('modal-copy-path-btn');
  if (copyBtn) { copyBtn.innerHTML = '&#128203; Copy path'; copyBtn.classList.remove('copied'); }
  document.getElementById('approve-modal').classList.add('open');
  setTimeout(function() { if (copyBtn) copyBtn.focus(); }, 50);
}
function closeApproveModal() {
  document.getElementById('approve-modal').classList.remove('open');
  if (_approveSourceBtn) _approveSourceBtn.focus();
}
document.getElementById('approve-modal').addEventListener('click', function(e) { if (e.target === this) closeApproveModal(); });

function copyApprovalPath() {
  var path = document.getElementById('modal-draft-path').value;
  navigator.clipboard.writeText(path).then(function() {
    var btn = document.getElementById('modal-copy-path-btn');
    btn.innerHTML = '&#10003; Copied';
    btn.classList.add('copied');
    setTimeout(function() { btn.innerHTML = '&#128203; Copy path'; btn.classList.remove('copied'); }, 2200);
    toast('Path copied — paste into the approve_draft workflow input.', { variant: 'success' });
  });
}

function _hideReviewUI(card) {
  var ra = card.querySelector('.review-actions'); if (ra) ra.style.display = 'none';
  var ab = card.querySelector('.approve-btn');   if (ab) ab.style.display = 'none';
}
function _updateStats(reviewDelta, approvedDelta) {
  document.querySelectorAll('.stat .l').forEach(function(el) {
    var n = el.previousElementSibling; if (!n) return;
    var t = el.textContent.trim();
    if (t === 'Needs review') n.textContent = Math.max(0, parseInt(n.textContent||'0') + reviewDelta);
    if (t === 'Approved')     n.textContent = Math.max(0, parseInt(n.textContent||'0') + approvedDelta);
  });
}

/* Auto-refresh draft cards on page load */
async function refreshDraftCards() {
  var cards = document.querySelectorAll('.card');
  var count = 0;
  for (var i = 0; i < cards.length; i++) {
    var card = cards[i];
    if (!card.querySelector('.badge.draft')) continue;
    var ab = card.querySelector('.approve-btn'); if (!ab) continue;
    var draftPath = ab.getAttribute('data-path'); if (!draftPath) continue;
    try {
      var url = 'https://raw.githubusercontent.com/' + _REPO + '/' + _BRANCH + '/' + draftPath + '?t=' + Date.now();
      var r = await fetch(url, { cache: 'no-store' }); if (!r.ok) continue;
      var data = await r.json();
      var badge = card.querySelector('.badge.draft'); if (!badge) continue;
      if (data.published || data.status === 'published') {
        badge.className = 'badge published'; badge.innerHTML = '✓ Published';
        _hideReviewUI(card); count++;
      } else if (data.approved || data.status === 'approved') {
        badge.className = 'badge approved'; badge.textContent = 'Approved';
        _hideReviewUI(card); count++;
      }
    } catch(e) {}
  }
  if (count > 0) _updateStats(-count, count);
}
window.addEventListener('load', refreshDraftCards);

/* Toast system */
function toast(message, opts) {
  opts = opts || {};
  var variant  = opts.variant || 'info';
  var sticky   = opts.duration === 0 || variant === 'error';
  var duration = opts.duration != null ? opts.duration : (variant === 'warning' ? 8000 : 5000);
  var container = document.getElementById('toast-container');
  while (container.children.length >= 3) container.firstElementChild.remove();
  var el = document.createElement('div');
  el.className = 'toast ' + variant;
  el.setAttribute('role', variant === 'error' ? 'alert' : 'status');
  el.setAttribute('aria-live', variant === 'error' ? 'assertive' : 'polite');
  el.setAttribute('aria-atomic', 'true');
  var icons = { success: '✓', error: '⚠', warning: '⚠', info: 'ⓘ' };
  var icon  = document.createElement('span'); icon.className = 'toast-icon'; icon.setAttribute('aria-hidden','true'); icon.textContent = icons[variant];
  var body  = document.createElement('div');  body.className = 'toast-body'; body.textContent = message;
  var close = document.createElement('button'); close.type = 'button'; close.className = 'toast-close';
  close.setAttribute('aria-label','Dismiss'); close.innerHTML = '&times;'; close.onclick = dismiss;
  el.appendChild(icon); el.appendChild(body); el.appendChild(close);
  container.appendChild(el);
  requestAnimationFrame(function() { el.classList.add('in'); });
  var timer = sticky ? null : setTimeout(dismiss, duration);
  el.addEventListener('mouseenter', function() { if (timer) { clearTimeout(timer); timer = null; } });
  el.addEventListener('mouseleave', function() { if (!sticky && !timer) timer = setTimeout(dismiss, 2000); });
  function dismiss() {
    if (timer) clearTimeout(timer);
    el.classList.remove('in'); el.classList.add('out');
    setTimeout(function() { if (el.parentNode) el.remove(); }, 200);
  }
  return dismiss;
}

/* ── FILTER CHIPS ── */
function filterCards(key) {
  document.querySelectorAll('.filter-chip').forEach(function(c) {
    c.classList.toggle('active', c.getAttribute('data-filter') === key);
  });
  var cards = document.querySelectorAll('.card');
  var shown = 0;
  cards.forEach(function(card) {
    var status = card.getAttribute('data-status') || '';
    var pillar = card.getAttribute('data-pillar') || '';
    var show = key === 'all' || key === status || key === pillar;
    card.style.display = show ? '' : 'none';
    if (show) shown++;
  });
  var lbl = document.querySelector('.section-lbl');
  if (lbl) lbl.textContent = 'Post history (' + shown + ')';
}
"""


# ---------------------------------------------------------------------------
# Per-pillar CSS rules injected at render time
# ---------------------------------------------------------------------------
def _pillar_class_css() -> str:
    lines = []
    for pillar, color in PILLAR_COLOR.items():
        alpha = color + "33"
        lines.append(f'.pillar-tag.{pillar}{{color:{color};background:{alpha};border-color:{color}55}}')
        lines.append(f'.card[data-pillar="{pillar}"]{{border-left-color:{color}}}')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Post card builder
# ---------------------------------------------------------------------------
def _card(post: dict, idx: int) -> str:
    pillar       = post.get("pillar", "unknown")
    status_value = post.get("status") or ""

    if   post.get("published") or status_value == "published":
        status = _badge("&#10003; Published", "published")
        status_key = "published"
    elif post.get("publish_error") or status_value == "failed":
        status = _badge("&#10007; Failed", "failed")
        status_key = "failed"
    elif post.get("approved") or status_value == "approved":
        status = _badge("Approved", "approved")
        status_key = "approved"
    elif post.get("dry_run"):
        status = _badge("Dry run", "dry-run")
        status_key = "dry-run"
    else:
        status = _badge("Needs review", "draft")
        status_key = "draft"

    raw_date = post.get("published_at") or post.get("generated_at", "")
    try:
        dt       = datetime.fromisoformat(raw_date.replace("Z", "+00:00"))
        date_str = _to_muscat(dt)
    except Exception:
        date_str = raw_date[:10]

    model_short = post.get("model", "unknown").replace("claude-", "").split(":")[0]
    attempts    = post.get("attempts", 1)
    char_count  = post.get("char_count", 0)
    char_pct    = min(100, (char_count / 1500) * 100)
    char_ok     = 800 <= char_count <= 1500
    char_cls    = "ok" if char_ok else "warn"

    topic     = html.escape(post.get("topic", ""))
    fmt       = html.escape(post.get("format", ""))
    post_text = html.escape(post.get("post", ""))

    alerts = ""
    if w := post.get("validation_warning"):
        alerts += f'<div class="alert warn">&#9888; {html.escape(w)}</div>'
    if e := post.get("publish_error"):
        alerts += f'<div class="alert error">&#10007; {html.escape(str(e)[:220])}</div>'

    metrics      = post.get("metrics") or {}
    metrics_html = ""
    if metrics:
        parts = []
        if (r := metrics.get("reactions"))            is not None: parts.append(f'<span class="metric-item">&#128077; {r}</span>')
        if (c := metrics.get("comments"))             is not None: parts.append(f'<span class="metric-item">&#128172; {c}</span>')
        if (s := metrics.get("shares"))               is not None: parts.append(f'<span class="metric-item">&#8635; {s}</span>')
        if (q := metrics.get("manual_quality_score")) is not None: parts.append(f'<span class="quality-score">&#9733; {q}/10</span>')
        if hs := metrics.get("hook_style"):                        parts.append(f'<span class="hook-tag">{html.escape(hs)}</span>')
        if parts:
            metrics_html = '<div class="metrics-row">' + "".join(parts) + "</div>"

    li_link = ""
    if post_id := post.get("post_id", ""):
        safe_id = html.escape(str(post_id))
        li_link = (
            f'<a class="li-link" href="https://www.linkedin.com/feed/update/{safe_id}/" '
            f'target="_blank" rel="noopener noreferrer">View on LinkedIn &#8599;'
            f'<span class="sr-only"> (opens in new tab)</span></a>'
        )

    fmt_html      = (f'<span class="fmt-tag">&#9999; {fmt[:42]}{"&#8230;" if len(fmt)>42 else ""}</span>' if fmt else "")
    attempts_html = f'<span class="retries">&#8635; {attempts} retries</span>' if attempts > 1 else ""

    needs_review = (
        (post.get("status") == "draft" or post.get("approval_required"))
        and not post.get("published")
    )
    filename      = post.get("_filename", "")
    draft_path    = html.escape(f"posts_history/{filename}") if filename else ""
    preview_val   = html.escape(post.get("post", "")[:400].replace("\n", " "))
    pillar_val    = html.escape(pillar)

    try:
        from content_strategy import PILLARS as _PILLARS
        publish_day = html.escape(_PILLARS.get(pillar, {}).get("publish_day", "next scheduled day"))
    except Exception:
        publish_day = "next scheduled day"

    review_actions = ""
    approve_btn    = ""
    if needs_review and draft_path:
        review_actions = f"""
        <div class="review-actions">
          <span class="review-label">Review:</span>
          <button class="rev-btn rev-changes" data-path="{draft_path}" data-pillar="{pillar_val}"
                  onclick="showReviseModal(this)">&#9998; Request Changes</button>
          <button class="rev-btn rev-edit" data-path="{draft_path}" data-preview="{preview_val}"
                  onclick="showEditModal(this)">&#128393; Edit</button>
          <button class="rev-btn rev-recreate" data-path="{draft_path}" data-pillar="{pillar_val}"
                  onclick="confirmRecreate(this)">&#8635; Recreate</button>
        </div>"""
        approve_btn = (
            f'<button class="approve-btn" '
            f'data-path="{draft_path}" data-preview="{preview_val}" '
            f'data-publish-day="{publish_day}" '
            f'onclick="showApproveModal(this)">&#10003; Approve for {publish_day}</button>'
        )

    return f"""
    <div class="card" id="post-{idx}" data-pillar="{pillar_val}" data-status="{status_key}">
      <div class="card-header">
        <span class="pillar-tag {pillar_val}">{pillar}</span>
        {status}
        <span class="meta-right">
          <span class="model-tag">{model_short}</span>
          <span class="date">{date_str}</span>
        </span>
      </div>
      {f'<div class="topic">{topic}</div>' if topic else ''}
      {f'<div class="fmt-row">{fmt_html}</div>' if fmt else ''}
      {alerts}
      {metrics_html}
      <div class="post-text collapsed" id="pt-{idx}">{post_text}</div>
      <button class="expand-btn" aria-expanded="false" aria-controls="pt-{idx}"
              onclick="toggle({idx})">Show more &#9660;</button>
      {review_actions}
      <div class="card-footer">
        <div class="bar-track"><div class="bar-fill {char_cls}" style="width:{char_pct:.1f}%"></div></div>
        <span class="chars {char_cls}">{char_count} chars</span>
        {attempts_html}
        {approve_btn}
        {li_link}
        <button class="icon-btn" id="copy-{idx}" onclick="copyPost({idx})">&#128203; Copy</button>
      </div>
    </div>"""


# ---------------------------------------------------------------------------
# Engagement sections (unchanged API surface, updated CSS classes)
# ---------------------------------------------------------------------------
def _engagement_sections() -> str:
    try:
        from engagement import get_repeat_engagers, load_all_engagement
        items    = load_all_engagement()
        engagers = get_repeat_engagers()
    except Exception:
        return ""

    RISK_COLOR   = {"safe": "#2a9a5c", "review": "#d4840a", "block": "#e8372a"}
    STATUS_COLOR = {"pending": "#d4840a", "approved": "#818cf8", "posted": "#2a9a5c", "blocked": "#e8372a"}

    pending       = [d for d in items if d.get("status") in ("pending", "approved")]
    recent_posted = [d for d in items if d.get("status") == "posted"][:5]

    if not pending:
        pending_html = '<div class="empty" style="padding:30px 20px">No pending replies</div>'
    else:
        cards = []
        for d in pending:
            risk    = d.get("risk_level", "review")
            status  = d.get("status", "pending")
            rc      = RISK_COLOR.get(risk, "#94a3b8")
            sc      = STATUS_COLOR.get(status, "#94a3b8")
            rec     = d.get("recommended_reply", 0)
            comment = html.escape(d.get("comment_text", "")[:200])
            topic   = html.escape(d.get("post_topic", ""))
            fname   = html.escape(Path(d.get("post_file", "engagement_history/?.json")).name)
            reply_rows = ""
            for i, r in enumerate(d.get("reply_drafts", [])):
                star = "&#9733; " if i == rec else ""
                reply_rows += (
                    f'<div class="reply-opt{"rec" if i==rec else ""}">'
                    f'<span class="reply-idx">{star}[{i}]</span> {html.escape(r)}</div>'
                )
            risk_cats = ", ".join(d.get("risk_categories", [])) or "none"
            risk_note = html.escape(d.get("risk_reason", ""))
            cards.append(f"""
            <div class="eng-card">
              <div class="eng-header">
                <span class="eng-badge" style="background:rgba(0,0,0,.3);color:{sc};border:1px solid {sc}44">{status.upper()}</span>
                <span class="eng-badge" style="background:rgba(0,0,0,.3);color:{rc};border:1px solid {rc}44">risk: {risk}</span>
                <span class="eng-meta">{topic[:55]}</span>
              </div>
              <div class="eng-comment">&#128172; {comment}</div>
              {f'<div class="eng-risk-note">&#9888; {html.escape(risk_cats)} &mdash; {risk_note}</div>' if risk=="review" else ""}
              <div class="eng-replies">{reply_rows or "<em>No reply drafts.</em>"}</div>
              <div class="eng-cmd"><code>python engagement.py approve {fname} --reply {rec}</code></div>
            </div>""")
        pending_html = "".join(cards)

    recent_html = ""
    if recent_posted:
        rp_rows = "".join(
            f'<div class="rp-item">&#10003; {html.escape(d.get("posted_reply","")[:100])}</div>'
            for d in recent_posted
        )
        recent_html = f'<h2 class="section-lbl" style="margin-top:22px">Recently posted replies ({len(recent_posted)})</h2>{rp_rows}'

    outreach_html = ""
    if engagers:
        lead_rows = "".join(
            f'<div class="lead-row">'
            f'<span class="lead-name">{html.escape(l.get("commenter_name",""))}</span>'
            f'<span class="lead-count">{l.get("post_count",0)} posts engaged</span>'
            f'<span class="lead-comment">{html.escape((l.get("comments") or [{}])[-1].get("comment_text","")[:80])}</span>'
            f'</div>'
            for l in engagers[:10]
        )
        outreach_html = (
            f'<h2 class="section-lbl" style="margin-top:28px">Outreach leads &mdash; repeat engagers ({len(engagers)})</h2>'
            f'<div class="leads-table">{lead_rows}</div>'
        )

    return f"""
    <div class="content" style="margin-top:0">
      <h2 class="section-lbl">Pending replies ({len(pending)})</h2>
      {pending_html}
      {recent_html}
      {outreach_html}
    </div>"""


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------
def generate(posts: list[dict]) -> str:
    total       = len(posts)
    n_published = sum(1 for p in posts if p.get("published") or p.get("status") == "published")
    n_drafts    = sum(1 for p in posts if (p.get("status") == "draft" or p.get("approval_required")) and not p.get("published"))
    n_approved  = sum(1 for p in posts if (p.get("approved") or p.get("status") == "approved") and not p.get("published"))
    n_failed    = sum(1 for p in posts if p.get("publish_error") or p.get("status") == "failed")
    success_pct = round((n_published / total * 100) if total else 0)

    scored_posts = [p for p in posts if (p.get("metrics") or {}).get("manual_quality_score") is not None]
    avg_score_html = ""
    if scored_posts:
        avg = round(sum(p["metrics"]["manual_quality_score"] for p in scored_posts) / len(scored_posts), 1)
        avg_score_html = f'<div class="stat"><div class="n">{avg}</div><div class="l">Avg score</div></div>'

    counts = Counter(p.get("pillar", "?") for p in posts)
    pillar_pills = "".join(
        f'<span class="pillar-pill" style="border-color:{PILLAR_COLOR.get(p,"#94a3b8")}55;'
        f'color:{PILLAR_COLOR.get(p,"#94a3b8")}">{p} <b>{c}</b></span>'
        for p, c in sorted(counts.items(), key=lambda x: -x[1])
    )

    from content_strategy import PILLARS
    gen_weekday_to_pillar = {c["generate_weekday"]: name for name, c in PILLARS.items()}

    def _run_html(r: datetime) -> str:
        pillar   = gen_weekday_to_pillar.get(r.weekday(), "?")
        config   = PILLARS.get(pillar, {})
        color    = PILLAR_COLOR.get(pillar, "#94a3b8")
        gen_date = (r + timedelta(hours=MUSCAT_OFFSET)).strftime("%a %b %d").replace(" 0", " ")
        pub_day  = config.get("publish_day", "")
        pub_sfx  = f' <span class="run-arrow">&rarr;</span> publishes {pub_day}' if pub_day else ""
        return (
            f'<span class="run-item">'
            f'<b>{gen_date}</b> &middot; 9:00 am Muscat &middot; '
            f'<span class="run-pillar" style="color:{color}">{pillar}</span>'
            f'{pub_sfx}'
            f'</span>'
        )

    runs_html = "".join(_run_html(r) for r in next_runs(3))

    _chip_defs = [
        ("All",          "all",       total),
        ("Needs review", "draft",     n_drafts),
        ("Published",    "published", n_published),
        ("Approved",     "approved",  n_approved),
    ]
    if n_failed:
        _chip_defs.append(("Failed", "failed", n_failed))
    for _p, _c in sorted(counts.items(), key=lambda x: -x[1]):
        _chip_defs.append((_p.capitalize(), _p, _c))
    filter_bar_html = (
        '<div class="filter-bar" role="group" aria-label="Filter posts">'
        + "".join(
            f'<button class="filter-chip{" active" if k == "all" else ""}" '
            f'data-filter="{k}" onclick="filterCards(\'{k}\')">'
            f'{n}<span class="count">{c}</span></button>'
            for n, k, c in _chip_defs
        )
        + "</div>"
    )

    token_msg, token_level = _token_health(posts)
    token_banner = ""
    if token_msg and token_level != "ok":
        icons = {"warn": "&#9888;", "error": "&#128308;", "info": "&#8505;"}
        icon  = icons.get(token_level, "&#8505;")
        renew = f'https://github.com/{REPO}/blob/main/LINKEDIN_SETUP.md'
        token_banner = (
            f'<div class="token-banner {token_level}">{icon} {html.escape(token_msg)} '
            f'<a href="{renew}" target="_blank" rel="noopener noreferrer">Renew token &rarr;</a></div>'
        )

    cards = "".join(_card(p, i) for i, p in enumerate(posts)) if posts else (
        '<div class="empty">&#128221;<br>No posts yet &mdash; '
        f'<a href="{ACTIONS_URL}" target="_blank" rel="noopener noreferrer">trigger the workflow</a>'
        ' to generate your first post.</div>'
    )

    now_muscat       = _to_muscat(datetime.now(timezone.utc))
    engagement_html  = _engagement_sections()
    branch           = _current_branch()
    pillar_class_css = _pillar_class_css()

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LinkedIn Auto-Poster &middot; Dashboard</title>
<style>{CSS_BASE}
{pillar_class_css}
</style>
</head>
<body>

<a href="#main-content" class="skip-link">Skip to posts<span class="sr-only"> (main content)</span></a>

<div class="topbar">
  <div class="logo">
    <span class="logo-mark" aria-hidden="true">LI</span>
    LinkedIn&nbsp;<em style="font-style:normal;color:#e8372a">Auto-Poster</em>
    <span class="logo-sep">/</span>
    Dashboard
  </div>
  <div class="topbar-right">
    <span class="updated">Updated {now_muscat}</span>
    <div class="live-dot" title="Live" aria-hidden="true"></div>
    <nav class="actions" aria-label="Site actions">
      <a class="tb-btn primary" href="{ACTIONS_URL}" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">&#9654;</span> Run workflow<span class="sr-only"> (opens in new tab)</span></a>
      <a class="tb-btn" href="https://github.com/{REPO}/actions" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">&#128200;</span> All runs<span class="sr-only"> (opens in new tab)</span></a>
      <a class="tb-btn" href="https://www.linkedin.com/in/" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">&#128279;</span> LinkedIn<span class="sr-only"> (opens in new tab)</span></a>
    </nav>
  </div>
</div>

{token_banner}

<div class="statsbar">
  <div class="stat"><div class="n">{total}</div><div class="l">Total</div></div>
  <div class="stat"><div class="n">{n_published}</div><div class="l">Published</div></div>
  <div class="stat"><div class="n">{n_drafts}</div><div class="l">Needs review</div></div>
  <div class="stat"><div class="n">{n_approved}</div><div class="l">Approved</div></div>
  <div class="stat"><div class="n">{n_failed}</div><div class="l">Failed</div></div>
  {avg_score_html}
  <div class="stat green"><div class="n">{success_pct}%</div><div class="l">Success</div></div>
  <div class="pillar-pills">{pillar_pills}</div>
</div>

<div class="schedbar">
  <span class="lbl">Next draft generation &rarr;</span>
  {runs_html}
</div>

{filter_bar_html}

<main id="main-content">
<div class="content">
  <h2 class="section-lbl">Post history ({total})</h2>
  {cards}
</div>

{engagement_html}

</main>

<footer>
  Drafts generated <b>Sat &middot; Mon &middot; Wed</b> at <b>9:00 am Muscat</b> &rarr; publishes <b>Mon &middot; Wed &middot; Fri</b> after manual approval &nbsp;&middot;&nbsp;
  <a href="https://github.com/{REPO}" target="_blank" rel="noopener noreferrer">Source<span class="sr-only"> (opens in new tab)</span></a> &middot;
  <a href="https://github.com/{REPO}/blob/main/LINKEDIN_SETUP.md" target="_blank" rel="noopener noreferrer">Renew LinkedIn token<span class="sr-only"> (opens in new tab)</span></a> &middot;
  <a href="{ACTIONS_URL}" target="_blank" rel="noopener noreferrer">Run workflow<span class="sr-only"> (opens in new tab)</span></a>
</footer>

<!-- Request Changes modal -->
<div class="modal-overlay" id="revise-modal" role="dialog" aria-modal="true" aria-labelledby="revise-modal-title">
  <div class="modal-box">
    <h3 id="revise-modal-title">&#9998; Request Changes</h3>
    <input type="hidden" id="revise-draft-path">
    <div class="modal-field">
      <span class="modal-label">Draft path</span>
      <code class="modal-path" id="revise-path-display"></code>
    </div>
    <div class="modal-field">
      <label class="modal-label" for="revise-notes">What should Claude change? Be specific.</label>
      <textarea class="modal-textarea" id="revise-notes" rows="4"
                placeholder="e.g. The opening is too generic. Make it start with a concrete dollar number or business outcome."
                aria-describedby="revise-pat-hint"></textarea>
    </div>
    <div class="modal-field">
      <label class="modal-label" for="revise-pat">GitHub Personal Access Token (workflow scope)</label>
      <input class="modal-input" id="revise-pat" type="password" placeholder="ghp_..." autocomplete="off" aria-describedby="revise-pat-hint">
      <div class="modal-hint" id="revise-pat-hint">Used to trigger the revision workflow. Token saved in browser localStorage.</div>
    </div>
    <div class="modal-status" id="revise-status" role="status" aria-live="polite"></div>
    <div class="modal-actions">
      <button class="modal-confirm" id="revise-confirm-btn" onclick="confirmRevise()">&#9998; Request Changes</button>
      <button class="modal-cancel" onclick="closeReviseModal()">Cancel</button>
    </div>
  </div>
</div>

<!-- Edit modal -->
<div class="modal-overlay" id="edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-modal-title">
  <div class="modal-box" style="max-width:680px">
    <h3 id="edit-modal-title">&#128393; Edit Draft</h3>
    <input type="hidden" id="edit-draft-path">
    <div class="modal-field">
      <label class="modal-label" for="edit-content">Edit the post text directly</label>
      <textarea class="modal-textarea" id="edit-content" rows="12" style="min-height:160px"></textarea>
      <div class="char-counter" id="edit-charcount">0 chars</div>
    </div>
    <div class="modal-field">
      <label class="modal-label" for="edit-pat">GitHub Personal Access Token (repo scope)</label>
      <input class="modal-input" id="edit-pat" type="password" placeholder="ghp_..." autocomplete="off" aria-describedby="edit-pat-hint">
      <div class="modal-hint" id="edit-pat-hint">Saves the edit directly to the repo as a commit.</div>
    </div>
    <div class="modal-status" id="edit-status" role="status" aria-live="polite"></div>
    <div class="modal-actions">
      <button class="modal-confirm" id="edit-confirm-btn" onclick="confirmEdit()">&#128190; Save Edit</button>
      <button class="modal-cancel" onclick="closeEditModal()">Cancel</button>
    </div>
  </div>
</div>

<!-- Approve modal -->
<div class="modal-overlay" id="approve-modal" role="dialog" aria-modal="true" aria-labelledby="approve-modal-title">
  <div class="modal-box">
    <h3 id="approve-modal-title">&#10003; Approve Draft</h3>
    <input type="hidden" id="modal-draft-path">
    <div class="modal-field">
      <span class="modal-label">Draft path</span>
      <code class="modal-path" id="modal-path-display"></code>
    </div>
    <div class="modal-field">
      <span class="modal-label">Post preview</span>
      <div class="modal-preview" id="modal-preview"></div>
    </div>
    <div class="modal-field">
      <span class="modal-label">Copy path for workflow input</span>
      <div style="margin-top:6px">
        <button class="icon-btn" id="modal-copy-path-btn" onclick="copyApprovalPath()">&#128203; Copy path</button>
      </div>
      <div class="modal-hint" style="margin-top:8px">
        Approve no longer requires a token. Click <b>Open Actions</b> below, choose <b>approve_draft</b>,
        paste the path above into the <em>draft_file</em> field, and run.
        The workflow commits the approval automatically &mdash; <b>post does not publish immediately</b>.
      </div>
    </div>
    <div class="modal-actions">
      <a class="modal-confirm approve-green" href="{ACTIONS_URL}" target="_blank" rel="noopener noreferrer"
         onclick="closeApproveModal()" style="display:inline-flex;align-items:center;gap:6px;text-decoration:none">
        Open Actions &#8599;<span class="sr-only"> (opens in new tab)</span></a>
      <button class="modal-cancel" onclick="closeApproveModal()">Close</button>
    </div>
  </div>
</div>

<div id="toast-container" aria-label="Notifications"></div>

<script>
var _REPO     = '{REPO}';
var _WORKFLOW = '{WORKFLOW_FILE}';
var _BRANCH   = '{branch}';
{JS_BODY}
</script>
</body>
</html>"""


if __name__ == "__main__":
    posts = load_posts()
    out   = DOCS_DIR / "index.html"
    out.write_text(generate(posts), encoding="utf-8")
