"""Generate a static HTML status dashboard from posts_history/.

Single-file generator. CSS and JS are kept as triple-quoted constants below
(no f-string brace escaping needed); only the HTML body shell uses f-string
interpolation, with a small set of substitution placeholders.

When changing visuals, modals, or behaviour: edit CSS_BASE / JS_BODY here, NOT
docs/index.html — that file is regenerated by this script on every workflow run.
"""

import html
import json
import subprocess
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

HISTORY_DIR   = Path(__file__).parent / "posts_history"
DOCS_DIR      = Path(__file__).parent / "docs"
DOCS_DIR.mkdir(exist_ok=True)

REPO          = "AbuAli85/LINKEDIN_POSTS"
WORKFLOW_FILE = "auto-post.yml"
ACTIONS_URL   = f"https://github.com/{REPO}/actions/workflows/{WORKFLOW_FILE}"


def _current_branch() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        return result.stdout.strip() or "main"
    except Exception:
        return "main"


PILLAR_COLOR = {
    "pain":       "#f87171",   # red   — urgency, problem
    "proof":      "#4ade80",   # green — results, success
    "vision":     "#818cf8",   # indigo — strategic, future
    "conversion": "#fbbf24",   # amber — CTA, offer
    # legacy pillar names kept so old published posts still render with a colour
    "leadership": "#818cf8",
    "ai":         "#22d3ee",
    "marketing":  "#fbbf24",
}

CRON_WEEKDAYS  = {5, 0, 2}  # Python weekday: Sat=5, Mon=0, Wed=2 — draft generation days
CRON_HOUR_UTC  = 5
MUSCAT_OFFSET  = 4   # UTC+4, no DST


def _to_muscat(dt: datetime) -> str:
    m = dt + timedelta(hours=MUSCAT_OFFSET)
    return m.strftime("%b %d, %Y · %I:%M %p Muscat").replace(" 0", " ").replace("AM", "am").replace("PM", "pm")


def load_posts() -> list[dict]:
    files = sorted(HISTORY_DIR.glob("*.json"), reverse=True)
    posts = []
    for f in files:
        try:
            p = json.loads(f.read_text(encoding="utf-8"))
            p["_filename"] = f.name
            posts.append(p)
        except Exception:
            continue
    return posts


def next_runs(n: int = 3) -> list[datetime]:
    now = datetime.now(timezone.utc)
    dt  = now.replace(hour=CRON_HOUR_UTC, minute=0, second=0, microsecond=0)
    if dt <= now:
        dt += timedelta(days=1)
    result = []
    for _ in range(14):
        if dt.weekday() in CRON_WEEKDAYS:
            result.append(dt)
        if len(result) >= n:
            break
        dt += timedelta(days=1)
    return result


def _token_health(posts: list[dict]) -> tuple[str, str]:
    """Return (message, level) where level is ok | warn | error | info | ''.

    NOTE: Expiry is estimated from the most-recent published post date because
    token_issued_at is not stored. For a more accurate countdown, store
    TOKEN_ISSUED_AT in a config file or GitHub secret when first authenticating.
    """
    published = [p for p in posts if p.get("published") and p.get("published_at")]
    if not published:
        return ("LinkedIn tokens expire after 60 days. Set a calendar reminder to renew yours.", "info")
    newest = max(published, key=lambda p: p.get("published_at", ""))
    try:
        created  = datetime.fromisoformat(newest["published_at"].replace("Z", "+00:00"))
        expires  = created + timedelta(days=60)
        days_left = (expires - datetime.now(timezone.utc)).days
        if days_left <= 0:
            return ("LinkedIn token has likely expired — renew immediately (see LINKEDIN_SETUP.md)", "error")
        if days_left <= 10:
            return (f"LinkedIn token expires in ~{days_left} days — renew now (see LINKEDIN_SETUP.md)", "error")
        if days_left <= 20:
            return (f"LinkedIn token expires in ~{days_left} days — plan renewal soon", "warn")
        return (f"LinkedIn token valid for ~{days_left} more days (estimated)", "ok")
    except Exception as exc:
        print(f"WARNING: _token_health parse error: {exc}", flush=True)
        return ("", "")


def _badge(text: str, cls: str) -> str:
    return f'<span class="badge {cls}">{text}</span>'


# ---------------------------------------------------------------------------
# STATIC CSS — single source of truth for dashboard styling.
# Includes: a11y (skip link, sr-only, :focus-visible, focus-visible touch targets),
# toast notifications, Batch 1 visual updates (sky-blue Approved badge, pillar
# left-edge accent, ghost-button li-link in card footer, etc.).
# ---------------------------------------------------------------------------
CSS_BASE = """
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0;min-height:100vh}
a{color:inherit;text-decoration:none}

/* SKIP LINK */
.skip-link{position:absolute;left:-9999px;top:8px;background:#0369a1;color:#fff;padding:8px 12px;border-radius:6px;z-index:300;font-size:.85rem;font-weight:600;text-decoration:none}
.skip-link:focus{left:8px}

/* SCREEN-READER ONLY */
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}

/* FOCUS */
:focus-visible{outline:2px solid #38bdf8;outline-offset:2px;border-radius:4px}

/* TOP BAR */
.topbar{background:#1e293b;border-bottom:1px solid #334155;padding:14px 24px;display:flex;flex-wrap:wrap;align-items:center;gap:10px}
.topbar h1{font-size:1.1rem;font-weight:700;color:#f1f5f9}
.topbar h1 em{color:#0ea5e9;font-style:normal}
.topbar .updated{font-size:.68rem;color:#94a3b8;margin-left:auto}
.actions{display:flex;gap:8px;margin-left:12px}
.btn{font-size:.75rem;padding:5px 12px;border-radius:6px;border:none;cursor:pointer;font-weight:500;text-decoration:none;display:inline-flex;align-items:center;gap:4px;min-height:40px}
.btn-primary{background:#0369a1;color:#fff}.btn-primary:hover{background:#025b96}
.btn-ghost{background:#1e293b;color:#94a3b8;border:1px solid #334155}.btn-ghost:hover{color:#f1f5f9;border-color:#475569}

/* TOKEN BANNER */
.token-banner{padding:10px 24px;font-size:.8rem;display:flex;align-items:center;gap:8px}
.token-banner.warn{background:#451a03;color:#fbbf24;border-bottom:1px solid #92400e}
.token-banner.error{background:#450a0a;color:#f87171;border-bottom:1px solid #7f1d1d}
.token-banner.info{background:#082f49;color:#7dd3fc;border-bottom:1px solid #0c4a6e}

/* STATS */
.statsbar{background:#1e293b;border-bottom:1px solid #334155;padding:12px 24px;display:flex;flex-wrap:wrap;gap:10px;align-items:center}
.stat{background:#0f172a;border:1px solid #334155;border-radius:8px;padding:9px 16px;text-align:center;min-width:68px}
.stat .n{font-size:1.4rem;font-weight:700;color:#f1f5f9;line-height:1.1}
.stat .l{font-size:.6rem;color:#94a3b8;text-transform:uppercase;letter-spacing:.06em;margin-top:3px}
.stat.success .n{color:#4ade80}
.pillar-pill{border:1px solid;border-radius:20px;padding:3px 11px;font-size:.75rem}
.pillar-pill b{color:#f1f5f9;margin-left:4px}

/* SCHEDULE */
.schedbar{background:#1e293b;border-bottom:1px solid #334155;padding:9px 24px;display:flex;flex-wrap:wrap;gap:14px;align-items:center;font-size:.8rem}
.schedbar .lbl{color:#94a3b8;font-size:.66rem;text-transform:uppercase;letter-spacing:.08em}
.run-item{color:#94a3b8}.run-item b{color:#f1f5f9}

/* CONTENT */
.content{max-width:820px;margin:0 auto;padding:22px 24px}
.section-lbl{font-size:.66rem;color:#94a3b8;text-transform:uppercase;letter-spacing:.1em;margin-bottom:12px}

/* CARD */
.card{background:#1e293b;border:1px solid #334155;border-left:3px solid #334155;border-radius:12px;padding:17px 19px;margin-bottom:13px;transition:border-color .15s}
.card:hover{border-color:#64748b}
.card-header{display:flex;flex-wrap:wrap;align-items:center;gap:7px;margin-bottom:8px}
.pillar-tag{font-size:.64rem;font-weight:700;text-transform:uppercase;letter-spacing:.07em}
.badge{font-size:.68rem;padding:3px 8px;border-radius:4px;font-weight:500}
.badge.published{background:#052e16;color:#4ade80}
.badge.approved{background:#082f49;color:#7dd3fc}
.badge.dry-run{background:#1c1917;color:#a8a29e}
.badge.draft{background:#1c1917;color:#fbbf24}
.badge.failed{background:#450a0a;color:#f87171}
.li-link{font-size:.68rem;background:#1e293b;color:#94a3b8;border:1px solid #334155;border-radius:5px;padding:5px 10px;min-height:40px;display:inline-flex;align-items:center;transition:all .15s;text-decoration:none}
.li-link:hover{border-color:#475569;color:#f1f5f9}
.meta-right{margin-left:auto;display:flex;gap:7px;align-items:center}
.model-tag{font-size:.65rem;background:#1a1a2e;color:#818cf8;border:1px solid #3730a3;padding:2px 7px;border-radius:4px}
.date{font-size:.68rem;color:#94a3b8}
.topic{font-size:.92rem;color:#e2e8f0;margin-bottom:6px}
.fmt-row{margin-bottom:9px}
.fmt-tag{font-size:.72rem;color:#94a3b8;background:#0f172a;border:1px solid #1e293b;border-radius:4px;padding:2px 7px}
.alert{border-radius:6px;padding:7px 11px;font-size:.76rem;margin-bottom:9px}
.alert.warn{background:#451a03;border:1px solid #92400e;color:#fbbf24}
.alert.error{background:#450a0a;border:1px solid #7f1d1d;color:#f87171}
.post-text{font-size:.87rem;line-height:1.78;color:#cbd5e1;white-space:pre-wrap;word-break:break-word}
.post-text.collapsed{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}
.expand-btn{background:none;border:none;color:#0ea5e9;font-size:.74rem;cursor:pointer;padding:8px 0;display:block;margin-top:4px;min-height:32px}
.expand-btn:hover{color:#38bdf8}
.card-footer{display:flex;align-items:center;gap:9px;margin-top:13px}
.bar-track{flex:1;height:3px;background:#334155;border-radius:2px;overflow:hidden}
.bar-fill{height:100%;border-radius:2px}
.bar-fill.ok{background:#22c55e}.bar-fill.warn{background:#f59e0b}
.chars{font-size:.68rem}.chars.ok{color:#4ade80}.chars.warn{color:#fbbf24}
.retries{font-size:.68rem;color:#f59e0b}
.copy-btn{background:#1e293b;border:1px solid #334155;color:#94a3b8;font-size:.68rem;padding:6px 12px;border-radius:5px;cursor:pointer;margin-left:auto;transition:all .15s;min-height:40px}
.copy-btn:hover{border-color:#475569;color:#f1f5f9}
.copy-btn.copied{border-color:#22c55e;color:#4ade80}
.review-actions{display:flex;flex-wrap:wrap;align-items:center;gap:7px;padding:9px 0 4px;border-top:1px solid #1e293b;margin-top:6px}
.review-label{font-size:.62rem;color:#94a3b8;text-transform:uppercase;letter-spacing:.08em;margin-right:2px}
.rev-btn{border:none;font-size:.71rem;font-weight:500;padding:7px 14px;border-radius:5px;cursor:pointer;transition:all .15s;min-height:40px}
.rev-changes{background:#2f1f05;color:#fbbf24;border:1px solid #92400e}.rev-changes:hover{background:#451a03}
.rev-edit{background:#1a1a2e;color:#818cf8;border:1px solid #3730a3}.rev-edit:hover{background:#1e1b4b}
.rev-recreate{background:#0f172a;color:#94a3b8;border:1px solid #334155}.rev-recreate:hover{color:#f1f5f9;border-color:#475569}
.approve-publish-btn{background:#0369a1;border:none;color:#fff;font-size:.72rem;font-weight:600;padding:7px 14px;border-radius:5px;cursor:pointer;transition:background .15s;min-height:40px}
.approve-publish-btn:hover{background:#025b96}
.empty{text-align:center;padding:60px 20px;color:#94a3b8;font-size:.95rem;line-height:2.4}
.empty a{color:#0ea5e9;border-bottom:1px solid #0ea5e9}
.modal-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:200;align-items:center;justify-content:center}
.modal-overlay.open{display:flex}
.modal-box{background:#1e293b;border:1px solid #334155;border-radius:14px;padding:28px 30px;max-width:560px;width:90%;max-height:88vh;overflow-y:auto}
.modal-box h3{color:#f1f5f9;font-size:1rem;margin-bottom:18px}
.modal-field{margin-bottom:14px}
.modal-label{font-size:.68rem;color:#94a3b8;margin-bottom:4px;display:block}
.modal-preview{font-size:.78rem;color:#cbd5e1;background:#0f172a;border-radius:6px;padding:9px 12px;line-height:1.65;max-height:110px;overflow-y:auto;white-space:pre-wrap;word-break:break-word}
.modal-path{font-size:.75rem;color:#94a3b8;font-family:monospace;background:#0f172a;padding:5px 9px;border-radius:5px;display:block}
.modal-pat{width:100%;padding:8px 10px;background:#0f172a;border:1px solid #334155;border-radius:6px;color:#e2e8f0;font-size:.82rem;outline:none}
.modal-pat:focus{border-color:#0ea5e9}
.modal-hint{font-size:.63rem;color:#94a3b8;margin-top:5px;line-height:1.4}
.modal-status{font-size:.78rem;min-height:20px;margin-bottom:12px}
.modal-actions{display:flex;gap:10px}
.modal-confirm{background:#0369a1;color:#fff;border:none;padding:10px 20px;border-radius:6px;cursor:pointer;font-size:.82rem;font-weight:600;min-height:40px}
.modal-confirm:hover{background:#025b96}
.modal-confirm:disabled{background:#334155;color:#94a3b8;cursor:default}
.modal-cancel{background:#1e293b;color:#94a3b8;border:1px solid #334155;padding:10px 18px;border-radius:6px;cursor:pointer;font-size:.82rem;min-height:40px}
.modal-cancel:hover{color:#f1f5f9;border-color:#475569}
.metrics-row{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin-bottom:9px}
.metric-item{font-size:.72rem;color:#94a3b8;background:#0f172a;border:1px solid #334155;border-radius:4px;padding:2px 8px}
.quality-score{font-size:.72rem;color:#fbbf24;background:#2f1f05;border:1px solid #92400e;border-radius:4px;padding:2px 8px;font-weight:600}
.hook-tag{font-size:.68rem;color:#818cf8;background:#1a1a2e;border:1px solid #3730a3;border-radius:4px;padding:2px 8px}
.eng-card{background:#1e293b;border:1px solid #334155;border-radius:10px;padding:14px 16px;margin-bottom:10px}
.eng-header{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-bottom:8px}
.eng-badge{font-size:.65rem;font-weight:600;padding:2px 8px;border-radius:4px}
.eng-meta{font-size:.68rem;color:#94a3b8;margin-left:auto}
.eng-comment{font-size:.82rem;color:#cbd5e1;background:#0f172a;border-radius:6px;padding:8px 11px;margin-bottom:8px;line-height:1.6}
.eng-risk-note{font-size:.72rem;color:#fbbf24;background:#451a03;border-radius:5px;padding:5px 10px;margin-bottom:8px}
.eng-replies{display:flex;flex-direction:column;gap:5px;margin-bottom:9px}
.reply-opt{font-size:.78rem;color:#94a3b8;background:#0f172a;border:1px solid #1e293b;border-radius:5px;padding:6px 10px;line-height:1.6}
.reply-optrec{border-color:#818cf855;color:#c7d2fe}
.reply-idx{font-size:.68rem;color:#94a3b8;font-weight:600;margin-right:4px}
.eng-cmd{font-size:.68rem;color:#94a3b8}
.eng-cmd code{background:#0f172a;border:1px solid #334155;border-radius:4px;padding:2px 7px;color:#94a3b8;font-family:monospace}
.rp-item{font-size:.78rem;color:#4ade80;background:#052e16;border-radius:5px;padding:5px 10px;margin-bottom:5px}
.leads-table{display:flex;flex-direction:column;gap:5px}
.lead-row{display:flex;flex-wrap:wrap;align-items:center;gap:10px;background:#1e293b;border:1px solid #334155;border-radius:8px;padding:8px 12px}
.lead-name{font-size:.8rem;color:#f1f5f9;font-weight:600;min-width:100px}
.lead-count{font-size:.68rem;color:#818cf8;background:#1a1a2e;border:1px solid #3730a3;border-radius:4px;padding:2px 8px}
.lead-comment{font-size:.74rem;color:#94a3b8;flex:1}

.run-pillar{text-transform:uppercase;font-size:.72rem;letter-spacing:.06em;font-weight:600}

footer{max-width:820px;margin:24px auto 0;padding:18px 24px 30px;border-top:1px solid #1e293b;color:#94a3b8;font-size:.74rem;line-height:1.7}
footer a{color:#94a3b8;border-bottom:1px dotted #475569}
footer a:hover{color:#f1f5f9}

@media(max-width:600px){
  .topbar,.statsbar,.schedbar,.content{padding-left:14px;padding-right:14px}
  .meta-right,.actions{display:none}
  .stat{padding:8px 12px}
}

/* TOAST */
#toast-container{position:fixed;bottom:24px;right:24px;z-index:250;display:flex;flex-direction:column;gap:8px;pointer-events:none;max-width:min(420px,calc(100vw - 48px))}
.toast{pointer-events:auto;background:#1e293b;border:1px solid #334155;border-radius:8px;padding:12px 14px;display:flex;gap:10px;align-items:flex-start;box-shadow:0 4px 12px rgba(0,0,0,.4);font-size:.82rem;line-height:1.5;opacity:0;transform:translateY(8px);transition:opacity .2s cubic-bezier(.16,1,.3,1),transform .2s cubic-bezier(.16,1,.3,1)}
.toast.in{opacity:1;transform:translateY(0)}
.toast.out{opacity:0;transform:translateX(12px);transition-duration:.18s;transition-timing-function:ease-in}
.toast.success{background:#052e16;border-color:#14532d;color:#4ade80}
.toast.error{background:#450a0a;border-color:#7f1d1d;color:#f87171}
.toast.warning{background:#2f1f05;border-color:#92400e;color:#fbbf24}
.toast.info{background:#082f49;border-color:#0c4a6e;color:#7dd3fc}
.toast-icon{font-size:1rem;flex-shrink:0;line-height:1.5}
.toast-body{flex:1;color:inherit}
.toast-action{background:transparent;border:1px solid currentColor;color:inherit;font-size:.74rem;font-weight:500;padding:4px 10px;border-radius:5px;cursor:pointer;margin-top:6px;min-height:32px}
.toast-action:hover{background:rgba(255,255,255,.08)}
.toast-close{background:transparent;border:none;color:inherit;opacity:.6;cursor:pointer;padding:0 2px;font-size:1.1rem;line-height:1;min-height:24px;min-width:24px}
.toast-close:hover,.toast-close:focus-visible{opacity:1}
@media(prefers-reduced-motion:reduce){
  .toast{transition:opacity .01s linear;transform:none}
  .toast.out{transform:none}
}
"""


# ---------------------------------------------------------------------------
# STATIC JS BODY — everything after the const declarations.
# Const declarations (_REPO, _WORKFLOW, _BRANCH) are emitted from generate()
# because they need values at render time.
# Toast component, focus management, modals, dashboard refresh logic.
# ---------------------------------------------------------------------------
JS_BODY = r"""
var _approveSourceBtn = null;
var _reviseSourceBtn = null;
var _editSourceBtn = null;
var _toastSeq = 0;

// Focus trap: cycle Tab/Shift+Tab within each modal box
document.querySelectorAll('.modal-box').forEach(function(box) {
  box.addEventListener('keydown', function(e) {
    if (e.key !== 'Tab') return;
    var sel = 'a[href],button:not([disabled]),textarea,input,[tabindex]:not([tabindex="-1"])';
    var els = [].slice.call(box.querySelectorAll(sel));
    if (!els.length) return;
    var first = els[0], last = els[els.length - 1];
    if (e.shiftKey) { if (document.activeElement === first) { e.preventDefault(); last.focus(); } }
    else { if (document.activeElement === last) { e.preventDefault(); first.focus(); } }
  });
});

// Escape closes the open modal, or the newest toast when no modal is open
document.addEventListener('keydown', function(e) {
  if (e.key !== 'Escape') return;
  var open = document.querySelector('.modal-overlay.open');
  if (open) {
    if (open.id === 'revise-modal') closeReviseModal();
    else if (open.id === 'edit-modal') closeEditModal();
    else if (open.id === 'approve-modal') closeApproveModal();
  } else {
    var c = document.getElementById('toast-container');
    var last = c && c.lastElementChild;
    if (last) last.querySelector('.toast-close').click();
  }
});

function toggle(i) {
  var t = document.getElementById('pt-' + i);
  var b = document.querySelector('#post-' + i + ' .expand-btn');
  if (t.classList.contains('collapsed')) {
    t.classList.remove('collapsed');
    b.setAttribute('aria-expanded', 'true');
    b.innerHTML = 'Show less <span aria-hidden="true">&#9650;</span>';
  } else {
    t.classList.add('collapsed');
    b.setAttribute('aria-expanded', 'false');
    b.innerHTML = 'Show more <span aria-hidden="true">&#9660;</span>';
  }
}
function copyPost(i) {
  var el = document.getElementById('pt-' + i);
  var collapsed = el.classList.contains('collapsed');
  if (collapsed) el.classList.remove('collapsed');
  var text = el.innerText;
  if (collapsed) el.classList.add('collapsed');
  navigator.clipboard.writeText(text).then(function() {
    var btn = document.getElementById('copy-' + i);
    btn.innerHTML = '<span aria-hidden="true">&#10003;</span> Copied';
    btn.classList.add('copied');
    setTimeout(function() {
      btn.innerHTML = '<span aria-hidden="true">&#128203;</span> Copy';
      btn.classList.remove('copied');
    }, 2000);
    toast('Post copied to clipboard.', { variant: 'success' });
  });
}

function _getPat() { return localStorage.getItem('gh_pat') || ''; }
function _setPat(v) { if (v) localStorage.setItem('gh_pat', v); }
function clearPat() { localStorage.removeItem('gh_pat'); toast('GitHub token cleared.', { variant: 'info' }); }

function showReviseModal(btn) {
  _reviseSourceBtn = btn;
  var path = btn.getAttribute('data-path');
  document.getElementById('revise-draft-path').value = path;
  document.getElementById('revise-path-display').textContent = path;
  document.getElementById('revise-notes').value = '';
  document.getElementById('revise-status').textContent = '';
  document.getElementById('revise-pat').value = _getPat();
  var cb = document.getElementById('revise-confirm-btn');
  cb.innerHTML = '<span aria-hidden="true">&#9998;</span> Request Changes';
  cb.disabled = false;
  document.getElementById('revise-modal').classList.add('open');
  setTimeout(function() { document.getElementById('revise-notes').focus(); }, 50);
}
function closeReviseModal() {
  document.getElementById('revise-modal').classList.remove('open');
  if (_reviseSourceBtn) _reviseSourceBtn.focus();
}
document.getElementById('revise-modal').addEventListener('click', function(e) { if (e.target === this) closeReviseModal(); });

async function confirmRevise() {
  var pat = document.getElementById('revise-pat').value.trim();
  var notes = document.getElementById('revise-notes').value.trim();
  var path = document.getElementById('revise-draft-path').value;
  var st = document.getElementById('revise-status');
  var cb = document.getElementById('revise-confirm-btn');
  if (!pat) { st.textContent = 'Error: Enter your GitHub PAT.'; st.style.color = '#f87171'; return; }
  if (!notes) { st.textContent = 'Error: Describe what needs to change.'; st.style.color = '#f87171'; return; }
  _setPat(pat);
  cb.textContent = 'Triggering…'; cb.disabled = true; st.textContent = '';
  try {
    var resp = await fetch('https://api.github.com/repos/' + _REPO + '/actions/workflows/' + _WORKFLOW + '/dispatches',
      { method: 'POST', headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
        body: JSON.stringify({ ref: _BRANCH, inputs: { action: 'revise_draft', draft_file: path, revision_notes: notes } }) });
    if (resp.status === 204) {
      closeReviseModal();
      toast('Revision requested — Claude is rewriting the draft.', { variant: 'success' });
    } else {
      var e = await resp.json().catch(function() { return {}; });
      st.textContent = 'Error ' + resp.status + ': ' + (e.message || 'check your PAT');
      st.style.color = '#f87171'; cb.innerHTML = '<span aria-hidden="true">&#9998;</span> Request Changes'; cb.disabled = false;
    }
  } catch(e) { st.textContent = 'Network error: ' + e.message; st.style.color = '#f87171'; cb.innerHTML = '<span aria-hidden="true">&#9998;</span> Request Changes'; cb.disabled = false; }
}

function showEditModal(btn) {
  _editSourceBtn = btn;
  var path = btn.getAttribute('data-path');
  var preview = btn.getAttribute('data-preview');
  document.getElementById('edit-draft-path').value = path;
  var ta = document.getElementById('edit-content');
  ta.value = preview;
  document.getElementById('edit-charcount').textContent = preview.length + ' chars';
  ta.oninput = function() { document.getElementById('edit-charcount').textContent = ta.value.length + ' chars'; };
  document.getElementById('edit-status').textContent = '';
  document.getElementById('edit-pat').value = _getPat();
  var cb = document.getElementById('edit-confirm-btn');
  cb.innerHTML = '<span aria-hidden="true">&#128190;</span> Save Edit';
  cb.disabled = false;
  document.getElementById('edit-modal').classList.add('open');
  setTimeout(function() { document.getElementById('edit-content').focus(); }, 50);
}
function closeEditModal() {
  document.getElementById('edit-modal').classList.remove('open');
  if (_editSourceBtn) _editSourceBtn.focus();
}
document.getElementById('edit-modal').addEventListener('click', function(e) { if (e.target === this) closeEditModal(); });

async function confirmEdit() {
  var pat = document.getElementById('edit-pat').value.trim();
  var path = document.getElementById('edit-draft-path').value;
  var content = document.getElementById('edit-content').value;
  var st = document.getElementById('edit-status');
  var cb = document.getElementById('edit-confirm-btn');
  if (!pat) { st.textContent = 'Error: Enter your GitHub PAT.'; st.style.color = '#f87171'; return; }
  if (!content.trim()) { st.textContent = 'Error: Post text cannot be empty.'; st.style.color = '#f87171'; return; }
  _setPat(pat);
  cb.textContent = 'Saving…'; cb.disabled = true; st.textContent = '';
  try {
    var metaResp = await fetch('https://api.github.com/repos/' + _REPO + '/contents/' + path,
      { headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json' } });
    if (!metaResp.ok) { var e = await metaResp.json().catch(function() { return {}; }); throw new Error('Could not read file: ' + (e.message || metaResp.status)); }
    var meta = await metaResp.json();
    var sha = meta.sha;
    var currentJson = JSON.parse(atob(meta.content.replace(/\n/g, '')));
    currentJson.post = content;
    currentJson.char_count = content.length;
    currentJson.manually_edited = true;
    currentJson.edited_at = new Date().toISOString();
    var newContent = btoa(unescape(encodeURIComponent(JSON.stringify(currentJson, null, 2))));
    var putResp = await fetch('https://api.github.com/repos/' + _REPO + '/contents/' + path,
      { method: 'PUT', headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: 'edit: manual draft revision via dashboard', content: newContent, sha: sha, branch: _BRANCH }) });
    if (putResp.status === 200 || putResp.status === 201) {
      closeEditModal();
      toast('Edit saved to repo. Refresh in ~30 seconds.', { variant: 'success' });
    } else {
      var e2 = await putResp.json().catch(function() { return {}; });
      st.textContent = 'Error ' + putResp.status + ': ' + (e2.message || 'check your PAT scope (needs repo)');
      st.style.color = '#f87171'; cb.innerHTML = '<span aria-hidden="true">&#128190;</span> Save Edit'; cb.disabled = false;
    }
  } catch(e) { st.textContent = 'Error: ' + e.message; st.style.color = '#f87171'; cb.innerHTML = '<span aria-hidden="true">&#128190;</span> Save Edit'; cb.disabled = false; }
}

function confirmRecreate(btn){
  var pillar=btn.getAttribute('data-pillar')||'same pillar';
  if(!confirm('Regenerate a new draft for the '+pillar+' pillar?\nThe current draft will remain in posts_history but will be replaced in the dashboard.'))return;
  var pat=_getPat();
  if(!pat){pat=prompt('Enter your GitHub PAT (workflow scope):');if(!pat)return;_setPat(pat);}
  fetch('https://api.github.com/repos/'+_REPO+'/actions/workflows/'+_WORKFLOW+'/dispatches',
    {method:'POST',headers:{'Authorization':'Bearer '+pat,'Accept':'application/vnd.github.v3+json','Content-Type':'application/json'},
      body:JSON.stringify({ref:_BRANCH,inputs:{action:'generate_draft',pillar:pillar}})
    }
  ).then(function(r){
    if(r.status===204){
      toast('New ' + pillar + ' draft generating — refresh in ~60 s.', { variant: 'success' });
    } else {
      r.json().then(function(e){
        toast('Error ' + r.status + ': ' + (e.message || 'check your PAT'), { variant: 'error' });
      }).catch(function(){ toast('Error ' + r.status, { variant: 'error' }); });
    }
  }).catch(function(e){ toast('Network error: ' + e.message, { variant: 'error' }); });
}

function _hideReviewUI(card){
  var ra=card.querySelector('.review-actions');
  if(ra) ra.style.display='none';
  var ab=card.querySelector('.approve-publish-btn');
  if(ab) ab.style.display='none';
}

function _updateStats(needsReviewDelta,approvedDelta){
  document.querySelectorAll('.stat .l').forEach(function(el){
    var n=el.previousElementSibling;
    if(!n) return;
    var t=el.textContent.trim();
    if(t==='Needs review') n.textContent=Math.max(0,parseInt(n.textContent||'0')+needsReviewDelta);
    if(t==='Approved') n.textContent=Math.max(0,parseInt(n.textContent||'0')+approvedDelta);
  });
}

async function refreshDraftCards(){
  var cards=document.querySelectorAll('.card');
  var count=0;
  for(var i=0;i<cards.length;i++){
    var card=cards[i];
    if(!card.querySelector('.badge.draft')) continue;
    var ab=card.querySelector('.approve-publish-btn');
    if(!ab) continue;
    var draftPath=ab.getAttribute('data-path');
    if(!draftPath) continue;
    try{
      var url='https://raw.githubusercontent.com/'+_REPO+'/'+_BRANCH+'/'+draftPath+'?t='+Date.now();
      var r=await fetch(url,{cache:'no-store'});
      if(!r.ok) continue;
      var data=await r.json();
      var badge=card.querySelector('.badge.draft');
      if(!badge) continue;
      if(data.published||data.status==='published'){
        badge.className='badge published';badge.innerHTML='&#10003; Published';
        var topicEl = card.querySelector('.topic');
        if (topicEl) toast('“' + topicEl.textContent.trim() + '” published on LinkedIn.', { variant: 'info' });
        _hideReviewUI(card);count++;
      }else if(data.approved||data.status==='approved'){
        badge.className='badge approved';badge.textContent='Approved';
        _hideReviewUI(card);count++;
      }
    }catch(e){}
  }
  if(count>0) _updateStats(-count,count);
}
window.addEventListener('load',refreshDraftCards);

function showApproveModal(btn) {
  _approveSourceBtn = btn;
  var path = btn.getAttribute('data-path');
  var preview = btn.getAttribute('data-preview');
  var day = btn.getAttribute('data-publish-day') || 'the scheduled day';
  document.getElementById('modal-draft-path').value = path;
  document.getElementById('modal-path-display').textContent = path;
  document.getElementById('modal-preview').textContent = preview;
  document.getElementById('modal-status').textContent = '';
  document.getElementById('modal-status').style.color = '';
  document.getElementById('approve-modal-title').innerHTML = '<span aria-hidden="true">&#10003;</span> Approve Draft → publishes ' + day;
  var cb = document.getElementById('modal-confirm-btn');
  cb.innerHTML = '<span aria-hidden="true">&#10003;</span> Approve for ' + day;
  cb.disabled = false;
  document.getElementById('modal-pat').value = _getPat();
  document.getElementById('approve-modal').classList.add('open');
  setTimeout(function() { document.getElementById('modal-pat').focus(); }, 50);
}

function closeApproveModal() {
  document.getElementById('approve-modal').classList.remove('open');
  if (_approveSourceBtn) _approveSourceBtn.focus();
}

document.getElementById('approve-modal').addEventListener('click', function(e) {
  if (e.target === this) closeApproveModal();
});

async function confirmApprove() {
  var pat = document.getElementById('modal-pat').value.trim();
  var draftPath = document.getElementById('modal-draft-path').value;
  var st = document.getElementById('modal-status');
  var cb = document.getElementById('modal-confirm-btn');
  if (!pat) { st.textContent = 'Error: Enter your GitHub PAT to continue.'; st.style.color = '#f87171'; return; }
  _setPat(pat);
  cb.textContent = 'Reading draft…'; cb.disabled = true; st.textContent = '';
  try {
    var getResp = await fetch('https://api.github.com/repos/' + _REPO + '/contents/' + draftPath,
      { headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json' } });
    if (!getResp.ok) {
      var ge = await getResp.json().catch(function() { return {}; });
      throw new Error('Could not read draft (' + getResp.status + '): ' + (ge.message || 'check PAT repo scope'));
    }
    var fileData = await getResp.json();
    var postJson = JSON.parse(atob(fileData.content.replace(/\n/g, '')));
    postJson.approved = true;
    postJson.status = 'approved';
    postJson.approval_required = false;
    postJson.approved_at = new Date().toISOString();
    postJson.dry_run = false;
    var encoded = btoa(unescape(encodeURIComponent(JSON.stringify(postJson, null, 2))));
    cb.textContent = 'Saving approval…';
    var putResp = await fetch('https://api.github.com/repos/' + _REPO + '/contents/' + draftPath,
      { method: 'PUT',
        headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: 'approve: ' + draftPath.split('/').pop(), content: encoded, sha: fileData.sha, branch: _BRANCH }) });
    if (putResp.status === 200 || putResp.status === 201) {
      var day = (_approveSourceBtn && _approveSourceBtn.getAttribute('data-publish-day')) || 'the scheduled day';
      if (_approveSourceBtn) {
        var card = _approveSourceBtn.closest('.card');
        if (card) {
          var badge = card.querySelector('.badge.draft');
          if (badge) { badge.className = 'badge approved'; badge.textContent = 'Approved'; }
          _hideReviewUI(card);
        }
        _updateStats(-1, 1);
      }
      closeApproveModal();
      toast('Approved — publishes ' + day + '.', { variant: 'success' });
    } else {
      var pe = await putResp.json().catch(function() { return {}; });
      st.textContent = 'Error ' + putResp.status + ': ' + (pe.message || 'check your PAT has repo contents write scope');
      st.style.color = '#f87171';
      cb.innerHTML = '<span aria-hidden="true">&#10003;</span> Approve'; cb.disabled = false;
    }
  } catch(e) {
    st.textContent = 'Error: ' + e.message;
    st.style.color = '#f87171';
    cb.innerHTML = '<span aria-hidden="true">&#10003;</span> Approve'; cb.disabled = false;
  }
}

function toast(message, opts) {
  opts = opts || {};
  var variant = opts.variant || 'info';
  var sticky = opts.duration === 0 || variant === 'error';
  var duration = opts.duration != null ? opts.duration : (variant === 'warning' ? 8000 : 5000);
  var id = opts.id || ('t' + (++_toastSeq));
  var container = document.getElementById('toast-container');

  while (container.children.length >= 3) container.firstElementChild.remove();

  var el = document.createElement('div');
  el.className = 'toast ' + variant;
  el.id = id;
  el.setAttribute('role', variant === 'error' ? 'alert' : 'status');
  el.setAttribute('aria-live', variant === 'error' ? 'assertive' : 'polite');
  el.setAttribute('aria-atomic', 'true');

  var icons = { success: '✓', error: '⚠', warning: '⚠', info: 'ⓘ' };
  var icon = document.createElement('span');
  icon.className = 'toast-icon';
  icon.setAttribute('aria-hidden', 'true');
  icon.textContent = icons[variant];

  var body = document.createElement('div');
  body.className = 'toast-body';
  body.textContent = message;

  if (opts.action) {
    var actionBtn = document.createElement('button');
    actionBtn.type = 'button';
    actionBtn.className = 'toast-action';
    actionBtn.textContent = opts.action.label;
    actionBtn.onclick = function() { try { opts.action.onClick(); } finally { dismiss(); } };
    body.appendChild(document.createElement('br'));
    body.appendChild(actionBtn);
  }

  var close = document.createElement('button');
  close.type = 'button';
  close.className = 'toast-close';
  close.setAttribute('aria-label', 'Dismiss notification');
  close.innerHTML = '&times;';
  close.onclick = dismiss;

  el.appendChild(icon);
  el.appendChild(body);
  el.appendChild(close);
  container.appendChild(el);

  requestAnimationFrame(function() { el.classList.add('in'); });

  var timer = sticky ? null : setTimeout(dismiss, duration);
  el.addEventListener('mouseenter', function() { if (timer) { clearTimeout(timer); timer = null; } });
  el.addEventListener('mouseleave', function() { if (!sticky && !timer) timer = setTimeout(dismiss, 2000); });
  el.addEventListener('focusin',    function() { if (timer) { clearTimeout(timer); timer = null; } });
  el.addEventListener('focusout',   function() { if (!sticky && !timer) timer = setTimeout(dismiss, 2000); });

  function dismiss() {
    if (timer) clearTimeout(timer);
    el.classList.remove('in');
    el.classList.add('out');
    setTimeout(function() { if (el.parentNode) el.remove(); }, 200);
  }
  return dismiss;
}
"""


def _pillar_class_css() -> str:
    """Generate per-pillar CSS rules from PILLAR_COLOR (data-driven)."""
    lines = []
    for pillar, color in PILLAR_COLOR.items():
        lines.append(f'.pillar-tag.{pillar}{{color:{color}}}')
        lines.append(f'.card[data-pillar="{pillar}"]{{border-left-color:{color}}}')
    return "\n".join(lines)


def _card(post: dict, idx: int) -> str:
    pillar = post.get("pillar", "unknown")

    status_value = post.get("status") or ""
    if post.get("published") or status_value == "published":
        status = _badge("&#10003; Published", "published")
    elif post.get("publish_error") or status_value == "failed":
        status = _badge("&#10007; Failed", "failed")
    elif post.get("approved") or status_value == "approved":
        status = _badge("Approved", "approved")
    elif post.get("approval_required") or status_value == "draft":
        status = _badge("Needs review", "draft")
    elif post.get("dry_run"):
        status = _badge("Dry run", "dry-run")
    else:
        status = _badge("Draft", "draft")

    raw_date = post.get("published_at") or post.get("generated_at", "")
    try:
        dt       = datetime.fromisoformat(raw_date.replace("Z", "+00:00"))
        date_str = _to_muscat(dt)
    except Exception:
        date_str = raw_date[:10]

    model_short  = post.get("model", "unknown").replace("claude-", "").split(":")[0]
    attempts     = post.get("attempts", 1)
    char_count   = post.get("char_count", 0)
    char_pct     = min(100, (char_count / 1500) * 100)
    char_ok      = 800 <= char_count <= 1500
    char_cls     = "ok" if char_ok else "warn"
    topic        = html.escape(post.get("topic", ""))
    fmt          = html.escape(post.get("format", ""))
    post_text    = html.escape(post.get("post", ""))

    alerts = ""
    if w := post.get("validation_warning"):
        alerts += f'<div class="alert warn">&#9888; {html.escape(w)}</div>'
    if e := post.get("publish_error"):
        alerts += f'<div class="alert error">&#10007; {html.escape(str(e)[:220])}</div>'

    metrics     = post.get("metrics") or {}
    metrics_html = ""
    if metrics:
        parts = []
        if (r := metrics.get("reactions")) is not None:
            parts.append(f'<span class="metric-item" title="Reactions">&#128077; {r}</span>')
        if (c := metrics.get("comments")) is not None:
            parts.append(f'<span class="metric-item" title="Comments">&#128172; {c}</span>')
        if (s := metrics.get("shares")) is not None:
            parts.append(f'<span class="metric-item" title="Shares">&#8635; {s}</span>')
        if (q := metrics.get("manual_quality_score")) is not None:
            parts.append(f'<span class="quality-score" title="Manual quality score">&#9733; {q}/10</span>')
        if hs := metrics.get("hook_style"):
            parts.append(f'<span class="hook-tag">{html.escape(hs)}</span>')
        if parts:
            metrics_html = '<div class="metrics-row">' + "".join(parts) + "</div>"

    # li-link now lives in the card-footer (D7/L4)
    li_link = ""
    if post_id := post.get("post_id", ""):
        safe_id = html.escape(str(post_id))
        li_link = (
            f'<a class="li-link" href="https://www.linkedin.com/feed/update/{safe_id}/" '
            f'target="_blank" rel="noopener noreferrer">View on LinkedIn &#8599;'
            f'<span class="sr-only"> (opens in new tab)</span></a>'
        )

    fmt_html      = f'<span class="fmt-tag" title="{fmt}">&#9999; {fmt[:38]}{"…" if len(fmt)>38 else ""}</span>' if fmt else ""
    attempts_html = f'<span class="retries">&#8635; {attempts} retries</span>' if attempts > 1 else ""

    needs_review = (
        (post.get("status") == "draft" or post.get("approval_required"))
        and not post.get("published")
    )
    filename       = post.get("_filename", "")
    draft_path_val = html.escape(f"posts_history/{filename}") if filename else ""
    preview_val    = html.escape(post.get("post", "")[:300].replace("\n", " "))
    pillar_val     = html.escape(pillar)

    from content_strategy import PILLARS as _PILLARS
    publish_day    = html.escape(_PILLARS.get(pillar, {}).get("publish_day", "next scheduled day"))

    review_actions = ""
    approve_btn    = ""
    if needs_review and draft_path_val:
        review_actions = f"""
  <div class="review-actions">
    <span class="review-label">Review:</span>
    <button class="rev-btn rev-changes" data-path="{draft_path_val}" data-pillar="{pillar_val}"
      onclick="showReviseModal(this)"><span aria-hidden="true">&#9998;</span> Request Changes</button>
    <button class="rev-btn rev-edit" data-path="{draft_path_val}" data-preview="{preview_val}"
      onclick="showEditModal(this)"><span aria-hidden="true">&#128393;</span> Edit</button>
    <button class="rev-btn rev-recreate" data-path="{draft_path_val}" data-pillar="{pillar_val}"
      onclick="confirmRecreate(this)"><span aria-hidden="true">&#8635;</span> Recreate</button>
  </div>"""
        approve_btn = (
            f'<button class="approve-publish-btn" '
            f'data-path="{draft_path_val}" data-preview="{preview_val}" '
            f'data-publish-day="{publish_day}" '
            f'onclick="showApproveModal(this)"><span aria-hidden="true">&#10003;</span> Approve for {publish_day}</button>'
        )

    return f"""
<div class="card" id="post-{idx}" data-pillar="{pillar_val}">
  <div class="card-header">
    <span class="pillar-tag {pillar_val}">{pillar}</span>
    {status}
    <span class="meta-right">
      <span class="model-tag">{model_short}</span>
      <span class="date">{date_str}</span>
    </span>
  </div>
  {f'<div class="topic">{topic}</div>' if topic else ''}
  {f'<div class="fmt-row">{fmt_html}</div>' if fmt else ''}
  {alerts}
  {metrics_html}
  <div class="post-wrap">
    <div class="post-text collapsed" id="pt-{idx}">{post_text}</div>
    <button class="expand-btn" aria-expanded="false" aria-controls="pt-{idx}" onclick="toggle({idx})">Show more <span aria-hidden="true">&#9660;</span></button>
  </div>
  {review_actions}
  <div class="card-footer">
    <div class="bar-track"><div class="bar-fill {char_cls}" style="width:{char_pct:.1f}%"></div></div>
    <span class="chars {char_cls}">{char_count} chars</span>
    {attempts_html}
    {approve_btn}
    {li_link}
    <button class="copy-btn" id="copy-{idx}" onclick="copyPost({idx})"><span aria-hidden="true">&#128203;</span> Copy</button>
  </div>
</div>"""


def _engagement_sections() -> str:
    """Build HTML for pending replies and outreach leads sections."""
    try:
        from engagement import get_repeat_engagers, load_all_engagement
        items   = load_all_engagement()
        engagers = get_repeat_engagers()
    except Exception:
        return ""

    RISK_COLOR = {"safe": "#4ade80", "review": "#fbbf24", "block": "#f87171"}
    STATUS_COLOR = {"pending": "#fbbf24", "approved": "#818cf8", "posted": "#4ade80",
                    "blocked": "#f87171"}

    pending = [d for d in items if d.get("status") in ("pending", "approved")]
    recent_posted = [d for d in items if d.get("status") == "posted"][:5]

    if not pending:
        pending_html = '<div class="empty" style="padding:30px 20px">No pending replies</div>'
    else:
        cards = []
        for d in pending:
            risk   = d.get("risk_level", "review")
            status = d.get("status", "pending")
            rc     = RISK_COLOR.get(risk, "#94a3b8")
            sc     = STATUS_COLOR.get(status, "#94a3b8")
            rec    = d.get("recommended_reply", 0)
            comment_esc = html.escape(d.get("comment_text", "")[:200])
            topic_esc   = html.escape(d.get("post_topic", ""))
            fname       = html.escape(Path(d.get("post_file", "engagement_history/?.json")).name)

            reply_rows = ""
            for i, r in enumerate(d.get("reply_drafts", [])):
                star   = "&#9733; " if i == rec else ""
                r_esc  = html.escape(r)
                reply_rows += (
                    f'<div class="reply-opt{"rec" if i == rec else ""}">'
                    f'<span class="reply-idx">{star}[{i}]</span> {r_esc}</div>'
                )

            risk_cats = ", ".join(d.get("risk_categories", [])) or "none"
            risk_note = html.escape(d.get("risk_reason", ""))

            cards.append(f"""
<div class="eng-card">
  <div class="eng-header">
    <span class="eng-badge" style="background:#0f172a;color:{sc};border:1px solid {sc}55">{status.upper()}</span>
    <span class="eng-badge" style="background:#0f172a;color:{rc};border:1px solid {rc}55">risk: {risk}</span>
    <span class="eng-meta">post: {topic_esc[:60]}</span>
  </div>
  <div class="eng-comment">&#128172; {comment_esc}</div>
  {f'<div class="eng-risk-note">&#9888; {html.escape(risk_cats)} &mdash; {risk_note}</div>' if risk == "review" else ""}
  <div class="eng-replies">{reply_rows if reply_rows else "<em>No reply drafts — blocked or fetch failed.</em>"}</div>
  <div class="eng-cmd"><code>python engagement.py approve {fname} --reply {rec}</code></div>
</div>""")
        pending_html = "".join(cards)

    if recent_posted:
        rp_rows = ""
        for d in recent_posted:
            posted_text = html.escape(d.get("posted_reply", "")[:100])
            rp_rows += f'<div class="rp-item">&#10003; {posted_text}</div>'
        recent_html = f'<h2 class="section-lbl" style="margin-top:22px">Recently posted replies ({len(recent_posted)})</h2>{rp_rows}'
    else:
        recent_html = ""

    if engagers:
        lead_rows = ""
        for lead in engagers[:10]:
            name  = html.escape(lead.get("commenter_name", "unknown"))
            urn   = html.escape(lead.get("commenter_urn", ""))
            count = lead.get("post_count", 0)
            latest_comment = html.escape((lead.get("comments") or [{}])[-1].get("comment_text", "")[:80])
            lead_rows += (
                f'<div class="lead-row">'
                f'<span class="lead-name">{name}</span>'
                f'<span class="lead-count">{count} posts engaged</span>'
                f'<span class="lead-comment">{latest_comment}</span>'
                f'</div>'
            )
        outreach_html = f"""
<h2 class="section-lbl" style="margin-top:28px">Outreach leads &mdash; repeat engagers ({len(engagers)})</h2>
<div class="leads-table">{lead_rows}</div>"""
    else:
        outreach_html = ""

    return f"""
<div class="content" style="margin-top:0">
  <h2 class="section-lbl">Pending replies ({len(pending)})</h2>
  {pending_html}
  {recent_html}
  {outreach_html}
</div>"""


def generate(posts: list[dict]) -> str:
    total       = len(posts)
    n_published = sum(1 for p in posts if p.get("published") or p.get("status") == "published")
    n_drafts    = sum(1 for p in posts if (p.get("status") == "draft" or p.get("approval_required")) and not p.get("published"))
    n_approved  = sum(1 for p in posts if (p.get("approved") or p.get("status") == "approved") and not p.get("published"))
    n_failed    = sum(1 for p in posts if p.get("publish_error") or p.get("status") == "failed")
    success_pct = round((n_published / total * 100) if total else 0)

    scored_posts = [p for p in posts if (p.get("metrics") or {}).get("manual_quality_score") is not None]
    avg_score_html = ""
    if scored_posts:
        avg = round(sum(p["metrics"]["manual_quality_score"] for p in scored_posts) / len(scored_posts), 1)
        avg_score_html = f'<div class="stat"><div class="n">{avg}</div><div class="l">Avg score</div></div>'

    counts = Counter(p.get("pillar", "?") for p in posts)
    pillar_pills = "".join(
        f'<span class="pillar-pill" style="border-color:{PILLAR_COLOR.get(p,"#94a3b8")}55;'
        f'color:{PILLAR_COLOR.get(p,"#94a3b8")}">{p} <b>{c}</b></span>'
        for p, c in sorted(counts.items(), key=lambda x: -x[1])
    )

    from content_strategy import PILLARS
    gen_weekday_to_pillar = {c["generate_weekday"]: name for name, c in PILLARS.items()}

    def _run_html(r: datetime) -> str:
        pillar     = gen_weekday_to_pillar.get(r.weekday(), "?")
        config     = PILLARS.get(pillar, {})
        color      = PILLAR_COLOR.get(pillar, "#94a3b8")
        gen_date   = (r + timedelta(hours=MUSCAT_OFFSET)).strftime("%a %b %d").replace(" 0", " ")
        pub_day    = config.get("publish_day", "")
        pub_suffix = f" <span style='color:#94a3b8'>&rarr; publishes {pub_day}</span>" if pub_day else ""
        return (
            f'<span class="run-item">'
            f'<b>{gen_date}</b>'
            f' &middot; 9:00 am Muscat'
            f' &middot; <span class="run-pillar" style="color:{color}">{pillar}</span>'
            f'{pub_suffix}'
            f'</span>'
        )

    runs_html = "".join(_run_html(r) for r in next_runs(3))

    token_msg, token_level = _token_health(posts)
    token_banner = ""
    if token_msg and token_level != "ok":
        icons = {"warn": "&#9888;", "error": "&#128308;", "info": "&#8505;"}
        icon  = icons.get(token_level, "&#8505;")
        token_banner = f'<div class="token-banner {token_level}">{icon} {html.escape(token_msg)}</div>'

    cards = "".join(_card(p, i) for i, p in enumerate(posts)) if posts else (
        '<div class="empty">&#128221;<br>No posts yet &mdash; '
        '<a href="' + ACTIONS_URL + '" target="_blank" rel="noopener noreferrer">trigger the workflow</a> to generate your first post.</div>'
    )

    now_muscat      = _to_muscat(datetime.now(timezone.utc))
    engagement_html = _engagement_sections()
    branch          = _current_branch()
    pillar_class_css = _pillar_class_css()

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LinkedIn Auto-Poster &middot; Dashboard</title>
<style>{CSS_BASE}
{pillar_class_css}
</style>
</head>
<body>

<a href="#main-content" class="skip-link">Skip to posts</a>

<div class="topbar">
  <h1>LinkedIn <em>Auto-Poster</em> &mdash; Dashboard</h1>
  <span class="updated">Updated {now_muscat}</span>
  <nav class="actions" aria-label="Site actions">
    <a class="btn btn-primary" href="{ACTIONS_URL}" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">&#9654;</span> Run workflow<span class="sr-only"> (opens in new tab)</span></a>
    <a class="btn btn-ghost" href="https://github.com/{REPO}/actions" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">&#128200;</span> All runs<span class="sr-only"> (opens in new tab)</span></a>
    <a class="btn btn-ghost" href="https://www.linkedin.com/in/" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">&#128279;</span> LinkedIn<span class="sr-only"> (opens in new tab)</span></a>
  </nav>
</div>

{token_banner}

<div class="statsbar">
  <div class="stat"><div class="n">{total}</div><div class="l">Total</div></div>
  <div class="stat"><div class="n">{n_published}</div><div class="l">Published</div></div>
  <div class="stat"><div class="n">{n_drafts}</div><div class="l">Needs review</div></div>
  <div class="stat"><div class="n">{n_approved}</div><div class="l">Approved</div></div>
  <div class="stat"><div class="n">{n_failed}</div><div class="l">Failed</div></div>
  {avg_score_html}
  <div class="stat success"><div class="n">{success_pct}%</div><div class="l">Success</div></div>
  {pillar_pills}
</div>

<div class="schedbar">
  <span class="lbl">Next draft generation &rarr;</span>
  {runs_html}
</div>

<main id="main-content">
<div class="content">
  <h2 class="section-lbl">Post history ({total})</h2>
  {cards}
</div>

{engagement_html}

</main>

<footer>
  Drafts generated <b>Sat &middot; Mon &middot; Wed</b> at <b>9:00 am Muscat</b> &rarr; publishes <b>Mon &middot; Wed &middot; Fri</b> after manual approval &nbsp;&middot;&nbsp;
  <a href="https://github.com/{REPO}" target="_blank" rel="noopener noreferrer">Source<span class="sr-only"> (opens in new tab)</span></a> &middot;
  <a href="https://github.com/{REPO}/blob/main/LINKEDIN_SETUP.md" target="_blank" rel="noopener noreferrer">Renew LinkedIn token<span class="sr-only"> (opens in new tab)</span></a> &middot;
  <a href="{ACTIONS_URL}" target="_blank" rel="noopener noreferrer">Run workflow<span class="sr-only"> (opens in new tab)</span></a>
</footer>

<!-- Request Changes modal -->
<div class="modal-overlay" id="revise-modal" role="dialog" aria-modal="true" aria-labelledby="revise-modal-title">
  <div class="modal-box">
    <h3 id="revise-modal-title"><span aria-hidden="true">&#9998;</span> Request Changes</h3>
    <input type="hidden" id="revise-draft-path">
    <div class="modal-field">
      <span class="modal-label">Draft path</span>
      <code class="modal-path" id="revise-path-display"></code>
    </div>
    <div class="modal-field">
      <label class="modal-label" for="revise-notes">What should Claude change? Be specific.</label>
      <textarea id="revise-notes" rows="4" placeholder="e.g. The opening is too generic. Make it start with a concrete dollar number or business outcome. Keep the list format but tighten each point to one sentence." style="width:100%;padding:8px 10px;background:#0f172a;border:1px solid #334155;border-radius:6px;color:#e2e8f0;font-size:.82rem;outline:none;resize:vertical;line-height:1.55"></textarea>
    </div>
    <div class="modal-field">
      <label class="modal-label" for="revise-pat">GitHub Personal Access Token (workflow scope)</label>
      <input class="modal-pat" id="revise-pat" type="password" placeholder="ghp_..." autocomplete="off" aria-describedby="revise-pat-hint">
      <div class="modal-hint" id="revise-pat-hint">Used to trigger the revision workflow. Token saved in browser localStorage.</div>
    </div>
    <div class="modal-status" id="revise-status" role="status" aria-live="polite"></div>
    <div class="modal-actions">
      <button class="modal-confirm" id="revise-confirm-btn" onclick="confirmRevise()"><span aria-hidden="true">&#9998;</span> Request Changes</button>
      <button class="modal-cancel" onclick="closeReviseModal()">Cancel</button>
    </div>
  </div>
</div>

<!-- Edit modal -->
<div class="modal-overlay" id="edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-modal-title">
  <div class="modal-box" style="max-width:680px">
    <h3 id="edit-modal-title"><span aria-hidden="true">&#128393;</span> Edit Draft</h3>
    <input type="hidden" id="edit-draft-path">
    <div class="modal-field">
      <label class="modal-label" for="edit-content">Edit the post text directly</label>
      <textarea id="edit-content" rows="12" style="width:100%;padding:9px 11px;background:#0f172a;border:1px solid #334155;border-radius:6px;color:#e2e8f0;font-size:.82rem;outline:none;resize:vertical;line-height:1.65;font-family:inherit;white-space:pre-wrap"></textarea>
      <div style="font-size:.64rem;color:#94a3b8;margin-top:4px" id="edit-charcount">0 chars</div>
    </div>
    <div class="modal-field">
      <label class="modal-label" for="edit-pat">GitHub Personal Access Token (repo scope)</label>
      <input class="modal-pat" id="edit-pat" type="password" placeholder="ghp_..." autocomplete="off" aria-describedby="edit-pat-hint">
      <div class="modal-hint" id="edit-pat-hint">Saves the edit directly to the repo as a commit.</div>
    </div>
    <div class="modal-status" id="edit-status" role="status" aria-live="polite"></div>
    <div class="modal-actions">
      <button class="modal-confirm" id="edit-confirm-btn" onclick="confirmEdit()"><span aria-hidden="true">&#128190;</span> Save Edit</button>
      <button class="modal-cancel" onclick="closeEditModal()">Cancel</button>
    </div>
  </div>
</div>

<!-- Approve modal -->
<div class="modal-overlay" id="approve-modal" role="dialog" aria-modal="true" aria-labelledby="approve-modal-title">
  <div class="modal-box">
    <h3 id="approve-modal-title"><span aria-hidden="true">&#10003;</span> Approve Draft</h3>
    <input type="hidden" id="modal-draft-path">
    <div class="modal-field">
      <span class="modal-label">Draft path</span>
      <code class="modal-path" id="modal-path-display"></code>
    </div>
    <div class="modal-field">
      <span class="modal-label">Post preview</span>
      <div class="modal-preview" id="modal-preview"></div>
    </div>
    <div class="modal-field">
      <label class="modal-label" for="modal-pat">GitHub Personal Access Token <em>(repo scope)</em></label>
      <input class="modal-pat" id="modal-pat" type="password" placeholder="ghp_..." autocomplete="off" aria-describedby="modal-pat-hint">
      <div class="modal-hint" id="modal-pat-hint">
        Marks the draft as approved &mdash; <b>does not publish immediately</b>. The cron will
        publish automatically on the scheduled day. &nbsp;
        <a href="#" onclick="clearPat();return false;">Clear saved token</a><br>
        Token is saved in browser localStorage and never sent anywhere except GitHub's API.<br>
        Create at <b>GitHub &rarr; Settings &rarr; Developer settings &rarr; Personal access tokens &rarr; Tokens (classic)</b>
        with <b>repo</b> scope (contents read/write).
      </div>
    </div>
    <div class="modal-status" id="modal-status" role="status" aria-live="polite"></div>
    <div class="modal-actions">
      <button class="modal-confirm" id="modal-confirm-btn" onclick="confirmApprove()"><span aria-hidden="true">&#10003;</span> Approve</button>
      <button class="modal-cancel" onclick="closeApproveModal()">Cancel</button>
    </div>
  </div>
</div>

<div id="toast-container" aria-label="Notifications"></div>

<script>
var _REPO = '{REPO}';
var _WORKFLOW = '{WORKFLOW_FILE}';
var _BRANCH = '{branch}';
{JS_BODY}
</script>
</body>
</html>"""


if __name__ == "__main__":
    posts = load_posts()
    out   = DOCS_DIR / "index.html"
    out.write_text(generate(posts), encoding="utf-8")
    print(f"Dashboard generated → {out}  ({len(posts)} posts)")
